nationalarchives/ds-caselaw-custom-api-client

src/caselawclient/xml_tools.py, tests/test_xml_tools.py
Metadata fields added are:
- Neutral Citation 
- Judgment Date
- Court
=> Add addtional metadata fields 

src/caselawclient/Client.py, src/caselawclient/xquery/get_last_modified.xqy
Add a function to retrieve the last time a document - or one if it's properties - was updated
=> Get last modified time

CHANGELOG.md, setup.cfg
Patch release to update `setup.cfg` and force a release of 4.5.0
=> Release v4.5.1

README.md
=> Add testing instructions to the README

src/caselawclient/xquery/set_metadata_this_uri.xqy
=> Typo: Two instances of FRBRthis which should be FRBRuri

CHANGELOG.md, setup.cfg
- Fix a typo in setting a judgment's internal URI
=> Release v4.7.1

setup.cfg
Forgotten step for release 4.8.0 🤦
=> Update version number in setup.cfg for v4.8.0

CHANGELOG.md, setup.cfg
- Add optional annotation parameter to `checkout_judgment` method
- Add method to get the lock/checkout status of a judgment
- Judgment checkout may optionally expire at midnight
=> Release v4.9.0

src/caselawclient/Client.py
Remove a debug `print()` statement that was missed
=> Remove a debug `print()` statement that was missed

src/caselawclient/Client.py
I was getting `TypeError: 'type' object is not subscriptable` when running the tests and this seems to be the fix.
=> Fix `TypeError: 'type' object is not subscriptable`

CHANGELOG.md, setup.cfg
- Ensure Work Date and Court values are returned as text
=> Release 5.1.2

.github/workflows/secrets.yml
This action will check the repository for committed secrets, and fail (allowing the user to take action) if they're present.
=> Add a check for secrets

README.md
This gives us a nice visual indication of what the current published version of this library is on pypi.
=> Add pypi version badge to readme

CHANGELOG.md, setup.cfg
=> Release 5.2.2

CHANGELOG.md, pyproject.toml
- Dependabot now updates dependencies for all new versions, not just security updates
- Use Poetry for dependency management, to improve robustness
- Add a `Judgment` class (copied from Editor Interface) to begin the process of harmonising how various services interface with the data
=> Release v5.3.0

CHANGELOG.md, pyproject.toml
- Fix broken build process where the package root was being incorrectly specified in the `pyproject.toml`.
=> Release v5.3.1

CHANGELOG.md, pyproject.toml
- Correct import location used in Judgment model, so it's usable when packaged
=> Release v5.3.2

src/caselawclient/content_hash.py, tests/content_hash/test_content_hash.py
This makes the content hashing module cleaner and more understandable, ready for the addition of lxml type stubs.
=> Clean up content hashing

CHANGELOG.md, pyproject.toml
Update changelog and pyproject.toml for v9.0.0 release
https://trello.com/c/T6x6GXmc/803-ensure-judgments-dont-display-press-summaries-erroneously
=> Update changelog and pyproject.toml for v9.0.0 release

pyproject.toml
https://trello.com/c/T6x6GXmc/803-ensure-judgments-dont-display-press-summaries-erroneously
Update pyproject.toml to v10.0.0
=> Update pyproject.toml to v10.0.0

CHANGELOG.md, pyproject.toml
Update pyproject.toml to v10.0.1
https://trello.com/c/T6x6GXmc/803-ensure-judgments-dont-display-press-summaries-erroneously
=> Update pyproject.toml to v10.0.1

.github/workflows/docs.yml, CHANGELOG.md, README.md, script/build_xquery_type_dicts, src/caselawclient/Client.py, src/caselawclient/__init__.py, src/caselawclient/client_helpers/search_helpers.py, src/caselawclient/models/__init__.py, src/caselawclient/models/documents.py, src/caselawclient/responses/__init__.py, src/caselawclient/responses/search_response.py, src/caselawclient/responses/search_result.py, src/caselawclient/xquery_type_dicts.py
Improve the in-code documentation, enriching our [generated documentation](https://nationalarchives.github.io/ds-caselaw-custom-api-client) in the process.
=> Improve client documentation

src/caselawclient/models/judgments.py, src/caselawclient/models/neutral_citation_mixin.py, src/caselawclient/models/press_summaries.py, tests/models/test_press_summaries.py
Exposed ncn property on PressSummary class.
https://trello.com/c/Xt3AAMES/1175-25-api-client-expose-ncnofrelatedjudgment-property-on-presssummary-class
**Still need to update changelog**
=> Expose ncn property on PressSummary class

CHANGELOG.md, pyproject.toml
=> Release 13.1.0

src/caselawclient/models/documents.py, src/caselawclient/models/judgments.py, src/caselawclient/models/press_summaries.py, tests/models/test_documents.py, tests/models/test_judgments.py, tests/models/test_press_summaries.py
Add a "best_human_identifier" to all Document classes for display purposes
=> Best human identifier

README.md, pyproject.toml, smoketest.py, src/caselawclient/xquery/set_metadata_court.xqy
There are some smoketests -- see the readme.
The xqy wasn't working at all. Now it does. And there's (bad) tests!
=> Fix court xqy crash bug

CHANGELOG.md, pyproject.toml
Update changelog and pyproject.toml version for release 14.0.1
=> Update changelog and pyproject.toml version for release 14.0.1

CHANGELOG.md, README.md, poetry.lock, pyproject.toml
Added  as a poetry  dependency to be able to run the new  file that connects to a MarkLogic instance.
=> Added  as a poetry  dependency to be able to run the new  file that connects to a MarkLogic instance.

src/caselawclient/models/documents.py, tests/models/test_documents.py
Fixes https://app.rollbar.com/a/dxw/fix/item/tna-caselaw-editor-ui/134?utm_campaign=new_item_message
=> Parse empty dates as None, warn on invalid non-empty dates

src/caselawclient/models/documents.py, tests/models/test_documents.py
We often need the most recent update time for the XML.
=> Get latest overall manifestation datetime

CHANGELOG.md, pyproject.toml
- Get version annotation for a single document
- Expose the type of the latest manifestation date of a document
=> Release v15.1.1

CHANGELOG.md, pyproject.toml
Release search highlighting functionality!
=> Version bump: v17.2.0

pyproject.toml, setup.cfg, src/caselawclient/models/documents.py, src/caselawclient/models/utilities/aws.py, tests/factories.py, tests/models/test_documents.py
https://trello.com/c/HMXLmwmk/1485-add-ability-for-editors-to-manually-trigger-a-document-reparse-proof-of-ability-to-reparse
=> Request Reparse

CHANGELOG.md, pyproject.toml
=> version bump v19.1.0

src/caselawclient/models/documents.py, tests/models/test_documents.py
`<document document/uri: Title>`
=> Ensure documents have sensible reprs

CHANGELOG.md, src/caselawclient/Client.py, src/caselawclient/xquery/get_highest_enrichment_version.xqy, src/caselawclient/xquery/get_highest_parser_version.xqy, src/caselawclient/xquery/get_pending_enrichment_for_version.xqy, src/caselawclient/xquery/get_pending_parse_for_version.xqy, src/caselawclient/xquery_type_dicts.py
These will be used to find documents in need of re-parsing.
=> Add API calls to get document parse information

CHANGELOG.md, pyproject.toml
=> version bump v22.0.1

CHANGELOG.md, pyproject.toml
=> Version bump 22.0.2

src/caselawclient/models/documents.py, tests/models/test_documents.py
Don't enrich if very recently sent to enrichment.
=> Only enrich if not recently called

CHANGELOG.md, src/caselawclient/responses/search_response.py, tests/conftest.py, tests/responses/test_search_response.py
Implement handling of facets within the API.
=> 1751 - Faceted Search

.pre-commit-config.yaml, CHANGELOG.md, assertions/assert.py, pyproject.toml, smoketest/smoketest.py, src/caselawclient/Client.py, src/caselawclient/models/documents.py, src/caselawclient/models/utilities/aws.py, tests/client/test_advanced_search.py, tests/client/test_client.py, tests/client/test_get_document_by_uri.py, tests/client/test_save_copy_delete_judgment.py, tests/client/test_search_parameters.py, tests/client_helpers/test_search_helpers.py, tests/client_helpers/test_version_annotation.py, tests/client_helpers/test_xml_helpers.py, tests/conftest.py, tests/content_hash/test_content_hash.py, tests/factories.py, tests/models/test_document_xml.py, tests/models/test_documents.py, tests/models/test_judgments.py, tests/models/test_press_summaries.py, tests/models/utilities/test_util_dates.py, tests/models/utilities/test_utilities.py, tests/responses/test_search_response.py, tests/responses/test_search_result.py, tests/xml_tools/test_xml_tools.py
Enable ruff on the API Client, run obvious auto-fixes, and enable some bare-bones rules to help improve code quality.
=> [FCL-217] Enable ruff on API Client

CHANGELOG.md, script/build_xquery_type_dicts, src/caselawclient/Client.py, src/caselawclient/xquery/get_pending_enrichment_for_version.xqy, src/caselawclient/xquery/get_pending_parse_for_version.xqy, src/caselawclient/xquery_type_dicts.py
https://national-archives.atlassian.net/browse/FCL-138
=> [FCL 138] Allow setting limits for reparse and bulk enrich

src/caselawclient/xquery/get_pending_enrichment_for_version.xqy
I'm not sure this the behaviour we actually want, given things should now be getting unlocked better?
=> require published before bulk enrichment

src/caselawclient/Client.py, src/caselawclient/xquery/get_recently_enriched.xqy, src/caselawclient/xquery/get_recently_parsed.xqy
=> Add functions to report on recently attempted enrichment and reparse

src/caselawclient/models/utilities/aws.py
We're having difficulty with a single file being published; these will help us understand why it's failing.
=> Log things that we try to copy in S3

pyproject.toml
Tiny bit of QoL improvement to our commitizen configuration.
=> ci(commitizen): make cz changelog incremental by default

src/caselawclient/Client.py
=> Fix typo leading to infinite recursion

CHANGELOG.md, pyproject.toml
- **Identifier**: update the types of outputs from value and slug
- **deps**: update dependency lxml to v5.3.1
=> bump: version 31.1.0 → 31.2.0

pyproject.toml
Update version in toml file to 32.0.0 for release
=> Update version in toml file to 32.0.0

src/caselawclient/responses/search_result.py, tests/responses/test_search_result.py
=> repr for SearchResult

.github/workflows/codeql.yml, .github/workflows/docs.yml, .github/workflows/publish.yml, .github/workflows/secrets.yml, .github/workflows/test.yml, .pre-commit-config.yaml
=> Use zizmor as a static ci linter

src/caselawclient/models/identifiers/press_summary_ncn.py, src/caselawclient/models/identifiers/unpacker.py, tests/models/identifiers/test_identifer_unpacking.py
Wants tests. Needed for ingester work.
=> Add press summary NCN identifiers to list of identifiers understood by unpacker

CHANGELOG.md, src/caselawclient/models/identifiers/fclid.py, src/caselawclient/models/identifiers/press_summary_ncn.py, tests/models/test_judgments.py, tests/models/test_press_summaries.py
This now closer matches reality with the identifier types under test.
=> [FCL-794] Correct behaviour of preferred_identifier and best_human_identifier

src/caselawclient/models/identifiers/neutral_citation.py, tests/models/identifiers/test_identifier_ncns.py
Update some NCN patterns to match reality now we're being harsher about some errors.
FCL-841
=> [FCL-841] Resolve NCN pattern matching for EWCOP T3

CHANGELOG.md, pyproject.toml
Release v36.0.2; allow EWCOP (T3) NCNs
=> release v36.0.2

CHANGELOG.md, src/caselawclient/factories.py
=> Include Identifiers in Search Result factories

pyproject.toml
=> Update toml to version 37.3.0

CHANGELOG.md, src/caselawclient/models/documents/__init__.py, src/caselawclient/models/utilities/__init__.py, tests/models/documents/test_documents.py, tests/models/utilities/test_utilities.py
=> [FCL-881] Improve behaviour of document versions

pyproject.toml
Update pyproject.toml for v 39.1.0
=> Update pyproject.toml for v 39.1.0

CHANGELOG.md, pyproject.toml
Update changelog and toml version for v39.2.0
=> Update changelog and toml version for v39.2.0
