nationalarchives/ds-caselaw-custom-api-client

- src/caselawclient/Client.py
- src/caselawclient/xml_tools.py
- src/caselawclient/xquery/set_boolean_property.xqy
- tests/test_client.py
Adds abstracted endpoint for getting and setting a property, regardless of data type. Slightly refactors the get_boolean_property function to extend the new get_property function to reduce duplication without changing the interface.
> Add setter and getter for properties

- CHANGELOG.md
- src/caselawclient/Client.py
- src/caselawclient/xquery/xslt_transform.xqy
- tests/test_client.py
The location of the images in the transformed Judgments will vary according to
environment. We need to pass the `image-base` to the XSLT to tell it where to
find the images.
This change relies on the implementing application having `XSLT_IMAGE_LOCATION`
set in its env.
> Pass image location to XSLT transform

- CHANGELOG.md
- src/caselawclient/Client.py
Note that the implementing application will have to add DATABASE_NAME to its
environment variables.
> Pass the name of the database the client uses in an env variable

- CHANGELOG.md
- setup.cfg
BREAKING CHANGES. This version will break your application unless it stores
the search XQuery on Marklogic as per https://github.com/nationalarchives/ds-caselaw-public-access-service
- Parameterize the location of images in the XSLT transformation
- Use the `invoke` endpoint, and the `search.xqy` stored on Marklogic, to search
- Remove the `database` parameter in `eval`, it's not required; the db associated with the REST server is used
> Release v4.0.0

- src/caselawclient/Client.py
- src/caselawclient/xml_tools.py
- tests/test_xml_tools.py
Use error code from eval response body to throw MarklogicResourceNotFound errors, as eval does not throw a 404
> Use error code from eval response body

- CHANGELOG.md
- src/caselawclient/xquery/set_metadata_name.xqy
We were assuming that the `akn:FRBRname` node would exist and could be edited,
but in some cases this node does not exist if the parser was unable to find a
case name in the judgment.
Check to see if a `akn:FRBRname` node exists in the document, and if it does
replace it, otherwise create a new one.
> Fix: If metadata name element does not exist, insert a new one as a child

- CHANGELOG.md
- setup.cfg
- Create a new `akn:FRBRname` node for the judgment metadata name, if one does not exist
> Release v4.5.2

- src/caselawclient/xquery/set_metadata_citation.xqy
- src/caselawclient/xquery/set_metadata_court.xqy
- src/caselawclient/xquery/set_metadata_date.xqy
Trello: https://trello.com/c/wqpbKBxw
In some judgments, the `<uk:court>` metadata element was entirely missing, instead of being present and incorrect. In these cases, we were not able to amend the court data as the XQuery to do this relies on the existence of a `uk:court` element to edit. The updated XQuery checks for the presence of the element, updates it if it exists, and creates it if it does not. 
Additionally, do the same amendments for the `uk:cite` and `akn:FRBRdate` elements.
> Allow editing of metadata if elements do not exist

- CHANGELOG.md
- setup.cfg
- Create a new `akn:FRBRdate`, `uk:cite` and `uk:court` nodes for the judgment
metadata, if they do not exist
> Release v4.5.3

- CHANGELOG.md
- src/caselawclient/Client.py
- src/caselawclient/xquery/xslt_transform.xqy
- tests/test_client.py
Allow the xsl filename used in the judgment transformation to vary.
We have two xsls available in Marklogic - `judgment2` (the accessible version)
and `judgment0` (the "as handed down" version).
Add two helper methods `accessible_judgment_transformation()` and
`original_judgment_transformation()` to call these transformations without
specifying the xsl filename.
> Allow the XSL filename used in judgment transformation to be varied

- CHANGELOG.md
- setup.cfg
- Allow the xsl filename used in the judgment transformation to vary. We have two xsls available in Marklogic -
`judgment2` (the accessible version) and `judgment0` (the "as handed down" version). Add two helper methods
`accessible_judgment_transformation()` and `original_judgment_transformation()` to call these transformations without
specifying the xsl filename.
- Copy judgment from URI to URI
> Release v4.6.0

- CHANGELOG.md
- src/caselawclient/xquery/get_last_modified.xqy
Change the behaviour of 'last-modified' dates to use prop:last-modified rather than xdmp:document-timestamp
Thomson Reuters reported an issue where on May 24th a great many documents started reporting their date in the
atom feed as being the 24th of May. From trawling through slack, it was discovered that this was co-incident
with a reindexing of the documents.
This implies that the xdmp:document-timestamp we are currently using is not fit for this purpose, so we have
changed the behaviour of the get_last_modified function to no-longer return this value.
prop:last-modified is a text string like 2022-07-04T11:05:45Z, but consumers expect a datetime;
documentation for the query string is at https://docs.marklogic.com/xdmp:parse-dateTime
The example gives an example of a 24h time being …
> Last modified use document timestamp

- src/caselawclient/Client.py
- src/caselawclient/xquery/set_metadata_this_uri.xqy
- tests/test_client.py
In https://github.com/nationalarchives/ds-caselaw-public-access-service/blob/main/marklogic/src/main/ml-modules/root/judgments/xslts/judgment2.xsl#L69
we can see that the XSLT uses the node at `/akomaNtoso/judgment/meta/identification/FRBRWork/FRBRthis/https://github.com/value`
to determine the URI of a document, and then uses that URI to build up a URL
for the judgment's images.
In judgments which have failed processing, and have had a Neutral Citation Number
(and therefore a URI) added manually by the editors, this internal URI at
`/FRBRWork/FRBRthis/https://github.com/value` remains blank.
This has the knock on effect of image URLs not resolving correctly in the HTML
version of a judgment (which is generated from the above XSLT).
This commit introduces an XQuery & API endpoint to set …
> Set the judgment's internal URI (`FRBRthis` and `FRBRuri` nodes)

- CHANGELOG.md
- src/caselawclient/xquery/delete_judgment.xqy
https://docs.marklogic.com/dls:document-delete
We were previously using xdmp:document-delete, which only deleted the document
itself.
As all our documents are managed under dls, it makes more sense to use
dls:document-delete, which will also delete the document's property history and
old versions. This way we do not end up with property fragments and versions of
old documents lying around.
https://trello.com/c/ZGmLoDby
> Change XQuery method for deleting documents

- src/caselawclient/xquery/get_last_modified.xqy
The approach taken was incorrect and the get_last_modified needed to not have a return as it did not have a let statement.
> Revert get_last_modified

- CHANGELOG.md
- setup.cfg
- Change the XQuery delete method from xdmp:document-delete to dls:document-delete
- Set the judgment's internal URI (`FRBRthis` and `FRBRuri` nodes)
> Release v4.7.0

- CHANGELOG.md
- src/caselawclient/xml_tools.py
- tests/test_xml_tools.py
If Marklogic is unavailable or returning an otherwise unexpected response, handle
the error more gracefully that previously. We were seeing AttributeErrors when
Marklogic was temporarily unavailable - this should handle them and return
something a bit more understandable than a 500 error response.
Trello: https://trello.com/c/rrdEvcje/731-improve-error-messaging-when-ml-is-unavailable
Rollbar: https://rollbar.com/dxw/tna-caselaw-public-ui/items/67/
> Gracefully handle a null, empty or unexpected error response from Marklogic

- CHANGELOG.md
- src/caselawclient/Client.py
- tests/test_client.py
`checkout_judgment` method requires an annotation parameter in its associated XQuery (`checkout_judgment.xqy`) but we weren't passing it in, and because we don't have any XQuery automated testing, and we're not yet using the `checkout_judgment` method, we didn't catch this error.
Additionally, add some new Marklogic error statuses associated with checking out a judgment.
> Correct error with `checkout_judgment` method

- CHANGELOG.md
- src/caselawclient/Client.py
- src/caselawclient/xquery/get_judgment_checkout_status.xqy
- tests/test_client.py
In the privileged API, we want to be able to see the checkout/lock status of a
judgment.
`get_judgment_checkout_status.xqy` checks the checkout status of a judgment using
`dls:document-checkout-status($uri)`
The result will either be empty, if the judgment is not locked, or an XML
fragment containing the URI and annotation message, if the judgment is locked.
The method `get_judgment_checkout_status` can be called on the Client, and will
return a response with either an XML fragment describing who has locked the
judgment, or empty if it is not locked.
The method `get_judgment_checkout_status_message` can also be called on the
Client, and will return either the lock annotation, if the judgment is locked,
or "not locked" if the judgment is not locked. …
> Add methods to get the lock/checkout status of a judgment

- CHANGELOG.md
- src/caselawclient/Client.py
- src/caselawclient/xquery/checkout_judgment.xqy
- tests/test_client.py
A comment on https://trello.com/c/l60TQkpe suggests the checkout/lock of
a judgment may expire at midnight, to ensure judgments aren't locked
"forever".
This commit adds a function `calculate_seconds_until_midnight` which calculates
how many seconds there are until midnight.
The Marklogic function `dls:document-checkout` contains an optional third
parameter which lets you pass in the amount of time in seconds a document
should be locked for.
Marrying these two up, we have amended `checkout_judgment` on the client to
take an optional `expires_at_midnight` parameter. Passing True to this param
means that the number of seconds until midnight is calculated, and passed to
`dls:document-checkout`.
If `expires_at_midnight` is not passed, an empty sequence `()` is used in
`dls:document-checkout` …
> Judgment checkout may optionally expire at midnight

- requirements.txt
- src/caselawclient/Client.py
- src/caselawclient/xquery/checkout_judgment.xqy
- src/caselawclient/xquery/get_judgment_checkout_status.xqy
- tests/test_client.py
While building the privileged API we encountered a few errors and issues with the API client:
- Error in checkout_judgment.xqy
- New version of requests required
- `get_judgment_checkout_status` returns a multipart response, which `get_judgment_checkout_status_message` needs to handle
- The `timeout` parameter must be passed to `checkout_judgment.xqy`, the parameter must be passed even if it is empty
> Correct various issues with the API Client

- CHANGELOG.md
- setup.cfg
- Fix: add external declaration to XQuery parameter
- Bump version of requests to 2.28.1
- Raise error if unpublished document is not returned
- Use -1 as value meaning 'lock forever' in checkout_judgment
- Return none if the judgment is not locked, rather than an empty string
> Release v4.9.1

- CHANGELOG.md
- src/caselawclient/Client.py
- src/caselawclient/xquery/user_has_privilege.xqy
- tests/test_client.py
A user has "privileges" in Marklogic, which are represented by names & IDs.
When we want to check to see if a user has a certain privilege, we can get the
ID of the privilege we want to check, then a sequence of the privileges a user
has, and see if the former is in the latter.
The XQuery `user_has_privilege` returns `true` or `false` depending on whether a requested privilege, which is found via its URI and action, is in the user's list of privileges. The method `user_has_privilege()`
returns a response object with a `text` value of `true` or `false`.
In https://github.com/nationalarchives/ds-caselaw-public-access-service/pull/65
we propose to add a custom privilege which indicates a user is allowed to view
unpublished judgments.
The second commit in this PR creates a method …
> Check if user can view unpublished documents

- script/test
- src/caselawclient/Client.py
- src/caselawclient/xquery/update_locked_judgment.xqy
- tests/test_client.py
Supports matching work in privileged api.
Two new errors for Checkout issues - not checkout out or checkout conflict
New function/xquery - save locked document
Work to move information about errors into the error subclasses to simplify downstream
(recommended error messages, status codes)
Little script for running the tests
> Changes for privileged client

- .github/workflows/test.yml
- README.md
- requirements.txt
- script/test
- src/caselawclient/Client.py
- tests/test_client.py
We have added `user_can_view_unpublished_judgments(self.username)` to the
client, which allows us to check that the currently logged in user (`username`)
has the appropriate permission to view unpublished judgments.
If a user attempts to access unpublished judgments by (somehow) calling an
endpoint with `show_unpublished=True` BUT they do not have the correct privilege
to view unpublished judgments, they should not be allowed to do that. Instead
`show_unpublished` will be set to False and they will not be able to see
unpublished judgments.
If a user who *is* allowed to view unpublished judgments asks specifically to
view unpublished judgments, by passing in `show_unpublished=False`, the value
of `show_unpublished` will remain False to allow them to view the required
unpublished judgments. …
> Ensure only people who are allowed to view unpublished judgments can view them

- src/caselawclient/Client.py
- src/caselawclient/xquery/break_judgment_checkout.xqy
- tests/client/test_checkout_checkin_judgment.py
Add the ability to break a checkout lock on a judgment. If a judgment is locked
we need a way to break the lock and return it to an editable state.
The XQuery uses `dls:break-checkout($uri, $deep)` to break the lock and
any locks on associated versions.
The function `break_checkout()` returns a request object containing no content
- the XQuery returns an empty sequence (assuming the requested URI exists).
https://trello.com/c/3eDUGYfk/837-implement-break-checkout-endpoint-function
> Break judgment checkout

- src/caselawclient/Client.py
- src/caselawclient/xquery/get_metadata_citation.xqy
- src/caselawclient/xquery/get_metadata_court.xqy
- src/caselawclient/xquery/get_metadata_work_date.xqy
- tests/client/test_get_set_metadata.py
- tests/client/test_get_set_properties.py
Currently we have XQuery-based methods for setting some metadata values, but not for getting them. Instead, the editor UI uses methods in XMLTools to get some of the metadata values ([example](https://github.com/nationalarchives/ds-caselaw-custom-api-client/blob/main/src/caselawclient/xml_tools.py#L18)). This is less efficient than using the XQuery-based methods, as it involves getting the entire document in memory, parsing it and picking out the desired values; using XQuery we can extract the values directly from Marklogic. 
This PR adds getters for all the metadata values we edit in the editor UI. It also adds some missing tests and moves some tests from TetGetSetProperties to a new TestGetSetMetadata file. 
https://trello.com/c/bqXeyL28/896-add-methods-to-get-set-all-metadata-in-the-cus …
> Methods & XQueries to get & set all metadata

- src/caselawclient/Client.py
- tests/client/test_client.py
`Client.py` is getting long. We should look into splitting/reducing it.
In the meantime, use three methods to DRY up the code a little:
1. We already had `self._format_uri()` but weren't using it everywhere. Use it everywhere!
2. We were repeatedly using `os.path.join` to get the XQuery file path. Add `self._xquery_path()` to remove this duplicated code and remove a few lines. 
3. Standardise all calls to `eval()` and then bundle them up into a helper method `self._send_to_eval()` and use this on all method calls.
> DRY up some aspects of the API Client

- src/caselawclient/Client.py
- tests/client/test_eval_xslt.py
In https://github.com/nationalarchives/ds-caselaw-public-access-service/pull/72
we will be renaming the XSL Transformation files in Marklogic from `judgment0`
and `judgment2` to `as-handed-down` and `accessible-html`, in order to be more
descriptive. This commit supports those changes.
https://trello.com/c/dylwn8lt/830-rename-judgment2-and-judgment0-xslts-in-public-access-service
> Support renaming of the XSL Transformation files

- src/caselawclient/Client.py
- tests/client/test_user_privileges.py
I was expecting the reponse from `self.user_has_privilege()` to be a plain text response but it is actually a multipart response.
Correct the method and test, to expect a multipart response, decode it, and check the boolean contents.
> (Fix) Incorrect response type expected in `user_can_view_unpublished_judgments()`

- requirements.txt
- setup.cfg
Ensure that dependencies (including the new `memoization`) are imported, so editor-ui etc don't have to know about custom-api-client's dependencies themselves.
Currently looks like it's working but need to convince myself it's right.
> Add dependencies to setup.cfg

- CHANGELOG.md
- requirements.txt
- src/caselawclient/Client.py
- tests/client/test_advanced_search.py
- tests/client/test_eval_xslt.py
- tests/client/test_user_privileges.py
- tests/client/test_verify_show_unpublished.py
When testing the API Client before a release, we noticed that the performance of the editor UI had degraded. The culprit is `verify_show_unpublished()` which checks that the active user has the right to view unpublished judgments. This is being called every time a user tried to view a judgment, or lists judgments. As a result, it was being called 10 times for each search result page. 
Our quick and inelegant (and hopefully temporary) solution is to use a rudimentary cache, which will check to see if the user has been through `user_can_view_unpublished_judgments` already, and if so use the result of that which is stored in the cache. 
This has made the editor UI faster in local testing.
The ultimate aim is to replace this with privilege checking within Marklogic.
> Speed up privilege checking

- CHANGELOG.md
- setup.cfg
Making this one a minor release as even though there are no changes the end users will see, there's been a lot of re-jigging under the hood.
- Add linting
- Ensure only people who are allowed to view unpublished judgments can view them
- Refactor tests
- Break judgment checkout
- Methods & XQueries to get & set all metadata
- DRY up some aspects of the API Client
- Support renaming of the XSL Transformation files
- Add memoization to speed up privilege checking
> Release v4.10.0

- src/caselawclient/Client.py
- tests/client/test_advanced_search.py
If a non-positive page is selected, force it to be the first page instead.
> Page 0 redirects to page 1

- src/caselawclient/Client.py
- src/caselawclient/xquery/user_has_role.xqy
- tests/client/test_user_privileges.py
- tests/client/test_user_roles.py
Allow users who have the `admin` role to view unpublished judgments.
This feels slightly backwards to me but unfortunately the `admin` role is not
editable in Marklogic, so granting the `admin` user the correct custom privilege
to view unpublished judgments is not immediately obvious.
As we have now figured out our custom roles in a previous PR (
https://github.com/nationalarchives/ds-caselaw-public-access-service/pull/86)
this work seems less urgent (as we can tailor our custom roles and should not
need to grant admin access to users). But it is still useful to be able to view
unpublished judgments as an admin user, for completeness.
There may be a way to grant this access via Marklogic's QBAC system
https://docs.marklogic.com/guide/security/qbac - for future investigation. …
> Admin users can't read unpublished judgments

- src/caselawclient/xml_tools.py
- tests/xml_tools/test_xml_tools.py
https://trello.com/c/X1IkTexF/883-refactor-xmltools-usage-in-eui
The XMLTools methods have been deprecated in favour of XQuery-based API calls.
Neither the editor UI nor the public UI use any XMLTools methods now. Deprecate these methods and remove them in a later major version.
> Deprecate XMLTools methods

- CHANGELOG.md
- setup.cfg
- Remove a debug `print()` statement that was missed
- Admin users can't read unpublished judgments
- Deprecate XMLTools methods
- Fix `TypeError: 'type' object is not subscriptable`
> Release v5.1.0

- src/caselawclient/Client.py
- tests/client/test_get_set_metadata.py
The get_judgment_citation function doesn't seem to be used anywhere else, so we can just change its output.
> Ensure Citations output as text rather than raw MarkLogic xml

- CHANGELOG.md
- setup.cfg
- src/caselawclient/Client.py
- src/caselawclient/xquery/get_properties_for_search_results.xqy
- tests/client/test_get_set_metadata.py
For multiple URIs, we can get multiple properties. Or pass a single item list if you only want data for one.
Current properties provided are:
**TDR Metadata**
source-name, source-email -- which clark sent the judgment?
transfer-consignment-reference -- TDR reference
transfer-received-at -- when was it sent?
**Editor Metadata**
editor-priority -- how important it is that the editors process this judgment
assigned-to -- which editor is responsible for this judgment?
editor-hold (not yet written to anywhere) -- is this judgment on hold?
https://trello.com/c/m8KuGSEk/33-%F0%9F%91%A9%F0%9F%92%BBeui-assign-judgments-http-endpoint
> Get properties for a list of search results

- src/caselawclient/Client.py
- tests/client/test_get_set_metadata.py
In https://github.com/nationalarchives/ds-caselaw-custom-api-client/pull/94
we changed the output of `get_judgment_citation` to be the text value of the
citation, not the response. This Commit beings `get_judgment_court` and
`get_judgment_work_date` in line with that function.
These functions are not yet used anywhere so it's safe to amend them.
> Ensure Work Date and Court values are returned as text

- src/caselawclient/Client.py
If the court string is set to be empty in the editor, Marklogic returns only an empty byte string, which the MultipartDecoder will choke on.
We test for this case and return an empty Unicode string to mirror the usual output type.
> Don't crash if multipart data is actually an empty byte string.

- README.md
We don't use Github releases to actually *release* this project (we use a github action that publishes the package to PyPi) but we've been using the Github release feature to keep a record of them. Document this in the README.
> Add a note to the readme about github releases

- src/caselawclient/xquery/update_locked_judgment.xqy
- src/caselawclient/xquery/validate_all_documents.xqy
Invalid documents will fail with an error like:
```
<error-response xmlns="http://marklogic.com/xdmp/error">
<status-code>500</status-code>
<status>Internal Server Error</status>
<message-code>XDMP-VALIDATEUNEXPECTED</message-code>
<message>XDMP-VALIDATEUNEXPECTED: (err:XQDY0027) validate strict { $judgment_xml } -- Invalid node: Found {http://docs.oasis-open.org/legaldocml/ns/akn/3.0}DragonMangledThisNode but expected ({http://docs.oasis-open.org/legaldocml/ns/akn/3.0}FRBRuri*,{http://docs.oasis-open.org/legaldocml/ns/akn/3.0}FRBRalias*,...,{http://docs.oasis-open.org/legaldocml/ns/akn/3.0}FRBRauthoritative?) at fn:doc("")/*:akomaNtoso/*:judgment/*:meta/*:identification/*:FRBRWork/*:DragonMangledThisNode using schema "/akn-modified.xsd"</message>
<message-detail>
<message-title>Invalid …
```
> Validate against a schema when priv API document is uploaded

- src/caselawclient/xquery/set_metadata_work_expression_date.xqy
`ds-caselaw-public-access-service` is now `ds-find-caselaw-docs`.
> Update references to old documentation repository

- README.md
This puts tagging the release on `main` where it belongs, rather than the HEAD of the branch.
> Clarify release process documentation

- src/caselawclient/Client.py
We expose a new exception, `MarklogicValidationFailedError` which corresponds to a class of Marklogic errors starting `XDMP-VALIDATE`...
> Expose a MarklogicValidationFailed exception to support enrichment

- .gitignore
- .pre-commit-config.yaml
- requirements.txt
- src/caselawclient/Client.py
- src/caselawclient/content_hash.py
- tests/content_hash/test_content_hash.py
Implements https://github.com/nationalarchives/tna-judgments-parser/blob/main/src/akn/SHA256.cs
Gets the text of the judgment (ignoring the metadata section) and strips out all whitespace and SHA256 hashes it.
Had some problems with getting the linters to play nice: see #118 fora resolution.
* Is this the right place in the code base?
* Need to wire this up to stuff -- is that best done here or in priv-api etc.
> Check content hash

- src/caselawclient/xquery/set_metadata_court.xqy
The string "" will be interpreted as a request to delete the court tag entirely by MarkLogic.
According to the schema, the `<uk:court>` tag must have one of a number of specific values for the courts; the blank string is not one of them; an unknown court is represented by the absence of a `<uk:court>` tag.
> Blank court strings delete the <uk:court/> tag

- src/caselawclient/xquery/set_metadata_court.xqy
Alternatives include adding
`let $dummy := 'dummy'`
which allows the return to remain
> Remove 'return' from XQuery to fix court bug.

- src/caselawclient/Client.py
- src/caselawclient/content_hash.py
- src/caselawclient/errors.py
- tests/client/test_save_copy_delete_judgment.py
- tests/content_hash/test_content_hash.py
(i.e. when we receive something from the privileged API)
Includes pulling errors into another file to avoid circular references
> Add content hash validation when we save a locked judgment

- src/caselawclient/xquery/xslt_transform.xqy
[Trello](https://trello.com/c/VIVTctiL/534-make-invalid-version-uris-return-an-error-state)
`fn:doc` of a non-existant node returns `()`, which looks the same as no version doc being passed in the first place
> Do not default to current version if version doesn't exist

- src/caselawclient/xquery/xslt_transform.xqy
I deleted some code that I thought did nothing, but the side-effects were critical -- they changed the imagebase of the XSLT document, pointing at the location of the actual images.
Looks good locally.
We'll need to redeploy editor/public after this is on PyPI.
> Re-add the code that was pointing the XSLT to the assets

- setup.cfg
The existence of the `py.typed` file declares that this package implements PEP-561-compliant type annotations and is safe for type checkers (such as mypy) to evaluate.
> Add PEP-561 typing declaration

- pyproject.toml
We weren't explicitly providing the source directory to Poetry, which meant it wasn't able to build the package. Now we do.
> Explicitly provide the directory to package

- .github/workflows/publish.yml
The `master` branch of this action is no longer used. Instead, use an explicitly tagged release. This increases reproducibility, and also lets Dependabot spot when it needs updating.
> Use tagged release of pypi publish action

- .github/workflows/publish.yml
- .github/workflows/test.yml
Pinned versions are more robust (they aren't likely to change in ways which break our workflow), and can be identified for updates by Dependabot.
> Pin all instances of actions/checkout to v3

- src/caselawclient/models/judgments.py
This now correctly imports the judgment model, so that it doesn't run into a missing module problem when deployed.
> Correct relative import in judgment model

- .github/workflows/test.yml
At the moment we report coverage for all three test runs; we should really only report it for the most recent version.
> Only run coverage reporting on latest Python version

- .pre-commit-config.yaml
- script/build_xquery_type_dicts
- src/caselawclient/Client.py
- src/caselawclient/xquery_type_dicts.py
- tests/client/test_eval_xslt.py
- tests/client/test_save_copy_delete_judgment.py
This introduces a new script, `build_xquery_type_dicts`, which looks through the `.xqy` files in `src/caselawclient/xquery` and uses their contents to generate a new `xquery_type_dicts.py`. This file strictly declares all required and optional parameters for each query as `TypedDict`s, which in this case are subclassed via `MarkLogicAPIDict`.
`Client.py` requires that all `dict`s passed to `_send_to_eval` are instances of `MarkLogicAPIDict`, which means they will fail if they are not one of the `TypedDict`s generated by the script.
As a final belt-and-braces, generating these typings is added to pre-commit; changing the parameters in a `.xqy` file will cause changes to be made in `xquery_type_dicts.py`, which will in turn cause mypy to fail if they are incompatible with the current …
> Add strict typing for dicts used in MarkLogic queries

- CHANGELOG.md
- pyproject.toml
- Significantly more type annotations on `Client` and `Judgment` methods, including some which are stricter than before. This is potentially a *breaking change* if implementations have been relying on duck typing.
- Automatic generation of strict typing for XQuery files which run against MarkLogic.
- Improvements to the methods used in content hashing, which will be breaking changes if these are used downstream.
> Release v6.0.0

- src/caselawclient/models/judgments.py
- tests/models/test_judgments.py
At the moment the only thing which prevents a publication is the presence of a hold flag, but this is not the only state in which publishing a document is an invalid operation.
Add some more condition checks to the publish flow around a document's name, court code and NCN.
We should be able to expose a list of reasons a document isn't publishable, so we can relay them to editors.
> Prevent publication in more invalid states

- CHANGELOG.md
- pyproject.toml
- `Judgment.publish` method will now reject publication in more invalid states (must have a name, must have a valid NCN, must have a court code).
- Less strict version pinning of dependencies to give downstream package users more flexibility in resolving.
> Release v6.1.0

- CHANGELOG.md
- README.md
- src/caselawclient/Client.py
- src/caselawclient/errors.py
- src/caselawclient/models/judgments.py
- src/caselawclient/xquery/judgment_exists.xqy
- src/caselawclient/xquery_type_dicts.py
- tests/client/test_client.py
- tests/client/test_get_set_properties.py
- tests/models/test_judgments.py
The existing implementation is based on a misunderstanding of the `get_neutral_citation` implementation; this does not return an exception if the document doesn't exist, it returns an empty string.
Implement a new function which explicitly tests for the existence of a document or not, and use that as part of `Judgment.__init__`.
> Improve detection of when a judgment doesn't exist

- src/caselawclient/models/judgments.py
- tests/models/test_judgments.py
notes:
* Unlock is before we attempt to unpublish, as unpublishing is impossible whilst locked
* Unlocking an unlocked judgment is fine
https://trello.com/c/O8J1bxp7/861-publishing-and-unpublishing-quickly-causing-document-to-stay-locked-due-to-enrichment
> Unlock judgment on Judgment.unpublish()

- src/caselawclient/Client.py
- tests/client/test_advanced_search.py
When filtering by judgment collection in the PUI in https://github.com/nationalarchives/ds-caselaw-public-ui/pull/701/files, I realised it was nicer for `collections` to be a list rather than a comma-separated string - so this PR changes that.
- Adjust collections filter on advanced_search so that it is passed as a list of possible collection uri strings instead of a comma separated list in a string
- Added some empty string/space filtering to it, so that it doesn't error in the marklogic query due to spaces/empty strings as marklogic collection names must be valid uris and empty strings / strings with spaces are not valid. Could do more validation but I dont think its worth it for now and probably best to do in the marklogic query itself. These filters seemed simple enough to add though, …
> Make collections parameter a list in advanced_search

- .pre-commit-config.yaml
- CHANGELOG.md
- src/caselawclient/responses/search_response.py
- src/caselawclient/responses/search_result.py
- src/caselawclient/responses/xsl/search_match.xsl
- tests/responses/test_search_response.py
- tests/responses/test_search_result.py
NOTE: This is the updated version of https://github.com/nationalarchives/ds-caselaw-custom-api-client/pull/216 given the change in abstraction in https://github.com/nationalarchives/ds-caselaw-custom-api-client/pull/222/files
- Added `SearchResponse` and `SearchResult`, `SearchResultMetadata`. These come from shared code between PUI AND EUI.
Differences to pui and eui implementations:
- `SearchResponse` is a renamed version of `SearchResults`
- `SearchResultMetadata` was added - but was found only in editor ui (renamed from `SearchResultMeta`.) 
- As part of this, note that publicui currently has `author` in main `SearchResult` class and note that it also has `last_modified` whereas not included in `SearchResult` or `SearchResultMeta` in editor ui so added to `SearchResultMeta` here.
- …
> Abstract away search result parsing into apiclient

- CHANGELOG.md
- src/caselawclient/client_helpers/search_helpers.py
- tests/client_helpers/test_search_helpers.py
- tests/responses/test_search_response.py
- Added `search_judgments_and_parse_response` and `search_and_parse_response` in a `search_helpers` module to abstract away the search and parse away from clients (PUI and EUI) without bloating the main client itself as the main client generally just returns the xml string response.
- https://trello.com/c/T6x6GXmc/803-ensure-judgments-dont-display-press-summaries-erroneously
> Add search client helpers

- CHANGELOG.md
- src/caselawclient/models/judgments.py
- tests/models/test_judgments.py
This method returns a list of reasons why the judgment has failed validation and is not publishable, by iterating over a list of attributes of a judgment which must 'pass' in order for it to be considered publishable and appending their error message if they fail. This also means we can refactor `is_publishable` to lean on the same list of attributes to test, which reduces function complexity.
Take this opportunity to tidy up the organisation of tests, and to also make parser failure a publish-blocking condition.
> Introduce new Judgment.validation_failure_messages method

- CHANGELOG.md
- pyproject.toml
- `Judgment.validation_failure_messages` method for retrieving a list of strings with reasons a judgment cannot be published.
> Release v10.1.0

- src/caselawclient/models/judgments.py
- tests/models/test_judgments.py
Where the ingester detects that it cannot assign a URI to a document (for example, the document is claiming to have the same URI as an existing document and it needs manual version reconciliation) then it will assign a URI in the format `parked/{uuid}`.
This PR adds detection of those parked URIs to the API client; parked URIs cannot be published.
> Add detection of 'parked' URIs

- src/caselawclient/Client.py
- tests/client/test_get_set_metadata.py
When setting a judgement's neutral citation, make sure we're not also including leading/trailing whitespace.
> Trim whitespace when trying to set an NCN

- renovate.json
Once https://github.com/nationalarchives/ds-find-caselaw-docs/pull/139 is merged, use that config instead of a repo-specific one.
> Switch Renovate to use the new global FCL config

- CHANGELOG.md
- src/caselawclient/Client.py
- src/caselawclient/models/documents.py
- src/caselawclient/models/judgments.py
- src/caselawclient/responses/search_result.py
- src/caselawclient/xml_helpers.py
- src/caselawclient/xml_tools.py
- src/caselawclient/xquery/get_metadata_citation.xqy
- src/caselawclient/xquery/get_metadata_court.xqy
- src/caselawclient/xquery/get_metadata_name.xqy
- src/caselawclient/xquery/get_metadata_work_date.xqy
- src/caselawclient/xquery_type_dicts.py
- tests/client/test_get_set_metadata.py
- tests/models/test_documents.py
- tests/models/test_judgments.py
- Refactor Document class to reduce calls to marklogic for the metadata
-  In particular updated `name`, `court`, `document_date_as_string` and `document_date_as_date` (previously `judgment_date_...`) on Document class and `neutral_citation` on Judgment class.
- Added `xml_etree` cached property to Document class and adjusted content_as_html to be a cached_property also.
- Removed `get_judgment_name, get_judgment_citation, get_judgment_court, get_judgment_work_date` from the Client class and associated `.xqy` files.
https://trello.com/c/gEGuXxmq/1156-api-client-refactor-the-apiclient-document-class-to-store-xml-rather-than-querying-the-db-for-each-metadata
> Refactor Document class to reduce calls to marklogic for the metadata fields

- src/caselawclient/Client.py
- src/caselawclient/models/documents.py
- tests/models/test_documents.py
* Marklogic config doesn't touch these things -- getter/setter was generic boolean fields
* Ingester doesn't know about these things and does not explicitly set/reset them.
* Editor has already been tweaked to not get/set these things.
This is a BREAKING CHANGE to the API, and should be a major version when released.
https://trello.com/c/o2sNyDZ2/1170-remove-deprecated-sensitive-supplemental-anonymised-method-calls-from-api-and-marklogic
> 💔 [BREAKING CHANGE] Remove supplemental/anonymous/sensitive getters/setters 

- src/caselawclient/Client.py
- tests/client/test_client.py
- tests/client/test_get_set_metadata.py
This entire client class currently assumes that there is exactly one item coming from MarkLogic in a multipart response, or failing that the only useful part of the response is the first item. This is currently true, but will not necessarily be in the future (and is prone to flakiness in any case).
This moves handling of the multipart response and turning it into text into a distinct function which can be used in future to retrieve a list of results, and simplifies the existing `decode_multipart` function to return only the first result, or fail with a hard exception (because it would mean whatever is calling the method is expecting a single result in a context where multiple results have been returned).
This is potentially a **breaking change** since unexpected multiple returns now raise …
> 💔 [BREAKING] Better MarkLogic multipart response handling

- src/caselawclient/models/documents.py
To support re-sending enrichment messages either in bulk or individually, add a document.enrich() method that doesn't publish the judgment.
This might help support a /enrich editor endpoint or a "mass-enrich all these documents" tool.
> Document.enrich()

- src/caselawclient/models/documents.py
- src/caselawclient/models/judgments.py
- tests/models/test_documents.py
- tests/models/test_judgments.py
There seems to be some confusion caused by the tests containing `<root>` elements that these appear in the actual judgments and the XQuery should include them -- we remove these elements, reduce dependency on the judgment element (but we still need to take a look at the `.xqy` files) and make some of the tests more realistic.
(We should probably think about having some sample XML files for testing.)
> We don't have an element named root before akomaNtoso

- .github/workflows/docs.yml
- poetry.lock
- pyproject.toml
This is an API client with downstream users, and as such we should probably be doing a better job of documentation. This commit automates the building of documentation using
[pdoc](https://github.com/mitmproxy/pdoc/tree/main), as well as its publication to GitHub Pages.
> Automate generation/publication of documentation

- .github/workflows/docs.yml
We installed pdoc and its dependencies, but didn't actually run them within the Poetry environment, causing the action to fail.
> Run pdoc via poetry

- .github/workflows/docs.yml
- poetry.lock
- pyproject.toml
This was only installing pdoc and its dependencies, which is everything needed to generate the docs, but did not include things needed to actually end up with valid code for the documentation generator to parse.
These dependencies are now in an optional group so they're not installed automatically (eg we have no need for them in production, and most people have no need for them in dev).
> Fix poetry installation for docs generation

- src/caselawclient/models/documents.py
- tests/models/test_documents.py
- Remove unneeded uk namespace from document_date_as_string
- Improve judgment metadata tests and parametrize to cover press summaries
https://trello.com/c/6d4gLCnL/1163-2-make-metadata-name-court-date-work-for-press-summary-document-objects
> Task/expose press summary metadata/1163

- src/caselawclient/Client.py
- src/caselawclient/models/documents.py
- src/caselawclient/models/utilities/__init__.py
- tests/models/test_documents.py
- tests/models/test_judgments.py
- tests/models/test_press_summaries.py
Tiny bugfix release for a problem I uncovered when attempting to upgrade the editor UI to v13.0.0.
Marklogic returns strings with an encoding declaration, which are unsupported by lxml (which gives precedence to the encoding declaration in the xml itself - see [this stack overflow answer](https://stackoverflow.com/questions/28534460/lxml-etree-xml-valueerror-for-unicode-string)), and raises an ValueError with message "Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration." - this can be verified by attempting to access any judgment on staging markdown with version 13.0.0 of the client.
Instead, we can just preserve the marklogic response as bytes and pass them directly to lxml rather than decoding (and re-encoding later).
> Bugfix: Ensure marklogic responses are treated as unencoded bytes

- src/caselawclient/models/documents.py
- src/caselawclient/models/utilities/aws.py
- tests/models/test_documents.py
Running this against an instance of a `Document` (or subclass like `Judgment` or `PressSummary`) will remove the document from MarkLogic and S3.
A document _cannot_ be deleted if it is published, since this implies it as already been given a publicly accessible URI. A document must first be unpublished (hopefully triggering appropriate workflows for hadnling depublication with data reusers etc) before it can be deleted.
> Add new `Document.delete()` method

- src/caselawclient/Client.py
- src/caselawclient/xquery/set_metadata_court.xqy
- src/caselawclient/xquery/set_metadata_name.xqy
- src/caselawclient/xquery/set_metadata_work_expression_date.xqy
- tests/client/test_get_set_metadata.py
- Generalised the set judgment metadata Client methods to set document metadata methods
- specifically for name, court and date
Haven't done it for neutral citation as it's a bit more complicated. I think I will leave that for a followup PR.
Have tested manually by copying and pasting into my local marklogic server. Have considered moving these xqy files into our marklogic repo so we can test them there, which I still think is worth doing but we have considered setting up some sort of suite of E2E tests to make sure things are actually working when hooked up together.
The `set_judgment_name` and `set_judgment_court` methods have been renamed.
https://trello.com/c/lppwqc94/1169-api-client-tidy-up-allow-press-summary-metadata-name-court-date-and-related-ncn-to-be-edited
> 💔 Generalise set document metadata methods to deal with press summaries

- CHANGELOG.md
- src/caselawclient/models/documents.py
- tests/models/test_documents.py
- tests/models/test_judgments.py
- tests/models/test_press_summaries.py
The old `is_editable` property was very unclear. The new `failed_to_parse` property describes what it actually checks, as well as being tested.
As part of this, a document which has failed to parse is now unpublishable.
> Remove `is_editable` in favour of `failed_to_parse`

- smoketest.py
- src/caselawclient/Client.py
- src/caselawclient/xquery/document_collections.xqy
I'm not entirely happy with this.
Raising `fn:error(xs:QName("FCL_ERRORCODE"), "Description of Error"))` doesn't actually emit the error code in the 500 error that the API client receives. So we have to put that into the description.
The Python error currently is also not customised, looking like:
```E           caselawclient.errors.DocumentNotFoundError: 500 Server Error: Internal Server Error for url: ...:8011/LATEST/eval. Response body:
E           <error-response xmlns="http://marklogic.com/xdmp/error">
E             <status-code>500</status-code>
E             <status>Internal Server Error</status>
E             <message-code>FCL-DOCUMENTNOTFOUND No document at /not/a/real/url.xml</message-code>
E             <message>FCL-DOCUMENTNOTFOUND No document at /not/a/real/url.xml:</message> …
```
> Not found error for collections

- CHANGELOG.md
- src/caselawclient/models/press_summaries.py
- tests/models/test_press_summaries.py
- Fixed `neutral_citation` property to look within `preface` tag rather than `mainBody` for press summaries, due to updated parsing resulting in updated press summary xml structure.
https://trello.com/c/uJiohuAM/1269-eui-spelling-of-press-summary
> Fixed PressSummary `neutral_citation` property

- src/caselawclient/Client.py
- tests/client/test_client.py
Set the default user agent string to give the version of the custom api client, and have it overriddable by users of the client.
> Add default user agent string to custom api client

- script/build_xquery_type_dicts
- src/caselawclient/Client.py
- src/caselawclient/models/documents.py
- src/caselawclient/responses/search_result.py
- src/caselawclient/xquery_type_dicts.py
There is currently ambiguity about the types of strings which are being passed around, particularly with the overloaded term "URI". This uses `typing.NewType` to create some new types of `str` so we can be explicit in what we mean. These are:
- `Document.DocumentURIString`: Our generally accepted concept of a document's unique identifier
- `xquery_type_dicts.MarkLogicDocumentURIString`: A URI referring to a concrete document within MarkLogic
- `xquery_type_dicts.MarkLogicDocumentVersionURIString`: A subclass of the above, referring to a specific version of a document in MarkLogic
- `xquery_type_dicts.MarkLogicPrivilegeURIString`: A URI referring to a user privilege within MarkLogic.
To allow for this, the `build_xquery_type_dicts` script will interpret some variable names as always …
> Be more strict about the flavours of strings

- assertions/README.md
- assertions/all_latest_versions.xqy
- assertions/assert.py
- assertions/must_have_collection.xqy
- assertions/not_two_collections.xqy
https://trello.com/c/e1Dgn4o4/1314-add-a-simple-quick-marklogic-validation-so-that-docs-have-to-be-in-a-doctype-collection-press-summary-judgment
I think we should have a good, long think about whether we want to set up a read-only user for making these sorts of queries against a potentially production database.
> Test whether the database obeys our own integrity rules

- src/caselawclient/models/documents.py
- tests/models/test_documents.py
The `is_failure` parameter previously relied on checking the URI to determine if a failure state existed. This is a hangover from previous behaviour, but not one we want.
Change the behaviour so that it instead relies on checking other parameters which are indicative of a failure. At the moment this is only `failed_to_parse`, but this list may be expanded in the future.
> Change `is_failure` behaviour to rely on `failed_to_parse`

- .gitignore
- src/caselawclient/models/documents.py
- src/caselawclient/xml_helpers.py
- tests/models/test_documents.py
https://trello.com/c/ArC1muhC/1321-api-client-expose-date-time-metadata-for-each-version-for-version-page-changes-1306
Yields the most recent date of each type as a datetime.
> Access most recent transformation/enrichment dates

- tests/client_helpers/test_xml_helpers.py
> Add forgotten tests for helper

- CHANGELOG.md
- pyproject.toml
Update changelog and pyproject.toml version for release 15.0.0
> Update changelog and pyproject.toml version for release 15.0.0

- src/caselawclient/responses/search_result.py
Note that this changes the neutral citation function to return two arguably different things, but separating those out  feels like overcomplicating it to me.
> Neutral citation in search results includes press summaries.

- src/caselawclient/models/documents.py
- src/caselawclient/responses/search_result.py
- src/caselawclient/xquery/get_properties_for_search_results.xqy
- tests/models/test_documents.py
- tests/responses/test_search_result.py
This is potentially breaking behaviour since there is a new `published` value editor_status can emit or `new` for Document.status.
https://linear.app/tna/issue/FCL-82/status-in-search-results-doesnt-match-the-actual-status-of-the
But it turns out that the editor just displays this value, never really parsing it; seems to be true for the Document too.
Editor could do with a colour tweak for "new"
> Provide publication information when getting metadata for search results

- CHANGELOG.md
- pyproject.toml
- Search results for press summaries now include NCNs
- Search results now correctly include document status information
- Latest manifestation datetime is available for documents (including versions)
> Release v15.1.0

- src/caselawclient/models/documents.py
- tests/models/test_documents.py
a new `document.get_latest_manifestation_type` method which returns either "tna-enrich" or "transform" depending on the "name" property of the most recent manifestation date.
This is used in the versions table in the editor UI to annotate each version with it's 'version type', which helps editors better understand where each version came from.
https://trello.com/c/jyTZaNMi/1359-eui-version-history-add-column-to-table-to-indicate-type-of-version
> Expose how the latest version came into being

- CHANGELOG.md
- src/caselawclient/client_helpers/__init__.py
- tests/client/test_save_copy_delete_judgment.py
- tests/client_helpers/test_version_annotation.py
`automated` is a required boolean, indicating if the version is the result of an automated process or a human action.
`payload` is an optional structured dict of additional information, which may be parsed by other tools such as EUI to expose relevant details.
> Add `automated` and `payload` to `VersionAnnotation`

- src/caselawclient/Client.py
0.9 of types-request allows error.response to be None. We expect it never will be.
> Catch if the response is None to make typelinting happy

- CHANGELOG.md
- src/caselawclient/Client.py
- src/caselawclient/models/documents.py
- src/caselawclient/xquery/xslt_transform.xqy
- src/caselawclient/xquery_type_dicts.py
- tests/client/test_eval_xslt.py
- tests/models/test_documents.py
- tests/test_helpers.py
`document.content_as_html` now takes an optional `query` parameter which is preprocessed in the same manner as the search query, then used to highlight matching terms in the document, which are returned with a surrounding `<mark>` tag. This mark tag has an id which gives the number, in sequence of the match from 0..n in the form `mark_{x}`.
A new `document.number_of_mentions` method which takes a `query` parameter and returns the number of highlighted mentions returned in the html for the query
https://trello.com/c/tnpX6eJW/1412-search-highlight-term-within-a-judgment-feature-flag-test
> Highlight  query matches in document html

- src/caselawclient/models/utilities/aws.py
New judgments do not appear on staging. We suspect this may be due to the ACL issue encountered in ingestion.
> Do not set ACL because ACLs are deprecated

- CHANGELOG.md
- src/caselawclient/models/documents.py
- src/caselawclient/models/utilities/aws.py
- tests/models/test_documents.py
Tidy up some behaviours which allow us to manually request a document be enriched via the API.
> Enable triggering of enrichment

- src/caselawclient/client_helpers/search_helpers.py
- src/caselawclient/responses/search_response.py
- src/caselawclient/responses/search_result.py
- tests/client/test_search_and_decode_response.py
- tests/responses/test_search_response.py
- tests/responses/test_search_result.py
Searching currently relies on the static instance of `api_client` which is initialised at `Client` load-time to interface with the database and retrieve metadata.
This instance is deprecated and due for removal, so we need to fix this behaviour. Search should only ever use the `Client` instance it was called with, so we need to either inject the dependency down or refactor the behaviour so it can directly access the `Client`.
As part of this, we move factory methods out of `SearchResultMetadata` and `SearchResult`, which provides a cleaner separation of concerns and reduces the depth to which we need to make changes to account for removing `api_client`.
There should be no functional changes as a result of this PR, and it should be non-breaking for EUI and PUI.
> Refactor search to get rid of dependency on static `api_client` instance

- CHANGELOG.md
- src/caselawclient/Client.py
- src/caselawclient/__init__.py
- src/caselawclient/client_helpers/search_helpers.py
- src/caselawclient/responses/search_response.py
- src/caselawclient/responses/search_result.py
- tests/client/test_search_and_decode_response.py
- tests/responses/test_search_response.py
- tests/responses/test_search_result.py
**Review and merge https://github.com/nationalarchives/ds-caselaw-custom-api-client/pull/468 first!**
This instance which is initialised at load-time has been deprecated since v13.1.0, and all in-library references to it have been cleaned up in #468. No downstream code should be relying on this instance.
> Remove `api_client` instance which is initialised on load

- CHANGELOG.md
- src/caselawclient/models/documents.py
- src/caselawclient/models/utilities/__init__.py
- tests/models/test_documents.py
- tests/models/utilities/test_utilities.py
**Review and merge https://github.com/nationalarchives/ds-caselaw-custom-api-client/pull/472 first!**
Remove some unnecessary abstraction in how we identify if a document has failed to parse. At the same time, stop swallowing where a document is not XML (which should never happen) and fail hard with a specific exception instead.
> Clean up parser error handling

- src/caselawclient/Client.py
Technically a breaking change to the API but stops `api_client.set_published()` being a footgun that does nothing.
> ⚠️  Make parameter to set_published non-optional

- CHANGELOG.md
- src/caselawclient/Client.py
- src/caselawclient/models/documents.py
- src/caselawclient/xquery/get_pending_enrichment_for_version.xqy
- src/caselawclient/xquery_type_dicts.py
MarkLogic uses TDE to extract relevant fields and pop them into an SQL database, which we then query to get a report on documents waiting to be enriched.
> Get a list of documents waiting for enrichment

- CHANGELOG.md
- pyproject.toml
- **Breaking**: `Client.set_published` no longer has a default argument; you must always be explicit.
- **Feature:** New `Client.get_pending_enrichment_for_version` method finds documents which are not yet enriched with a given version, and which haven't recently been sent for enrichment.
> Release v19.0.0

- CHANGELOG.md
- src/caselawclient/responses/xsl/search_match.xsl
- src/caselawclient/search_parameters.py
- tests/client/test_advanced_search.py
- tests/client/test_search_parameters.py
This goes with a [marklogic PR](https://github.com/nationalarchives/ds-caselaw-marklogic/pull/50) which ensures that snippets containing quoted phrases in the query are given priority when they're displayed to users.
This PR provides the list of quoted phrases to marklogic (essentially impossible to do with marklogic's own regex engine), and also limits the number of matched phrases returned to 4 (the current default), as the number returned by marklogic itself has necessarily increased (we need to generate a larger amount of matches before prioritisation to ensure we catch any mentions of the quoted phrase).
https://trello.com/c/IQK3v7c5/1560-search-matching-text-should-reflect-search-query-in-quotations-over-other-words-in-search-results
> Prioritise quoted phrases in search snippets.

- smoketest/smoketest.py
- src/caselawclient/Client.py
- src/caselawclient/xquery/get_highest_enrichment_version.xqy
Does not necessarily reflect the version number in Enrichment. This might lead to scenarios where bulk enrichment is stalled until a single successful manual or new-document enrichment occurs.
> Return the highest enrichment version seen on MarkLogic

- poetry.lock
https://github.com/nationalarchives/ds-caselaw-custom-api-client/security/dependabot/6
> Update poetry dependencies, including security update for Jinja to 3.1.3

- src/caselawclient/models/documents.py
- src/caselawclient/models/utilities/aws.py
- tests/models/test_documents.py
Remove "published" as a thing that we send, we should check locally on import.
Reformat to nested format.
> Nested parser instructions

- CHANGELOG.md
- src/caselawclient/Client.py
- src/caselawclient/xquery/get_pending_enrichment_for_version.xqy
- src/caselawclient/xquery_type_dicts.py
There is no point enriching documents which haven't also been through the latest parser, since we know for a fact they will be re-parsed again shortly anyway.
This changes the enrichment backlog query to also require a parser version which documents must meet in order to qualify.
> Make pending enrichment query aware of parser version

- src/caselawclient/models/documents.py
- tests/models/test_documents.py
Discovered while running the tests while in GMT+1 - we should probably persist these dates in a timezone-agnostic format
> Fix datetime bug in last_enriched/last_parsed

- CHANGELOG.md
- src/caselawclient/Client.py
- src/caselawclient/models/documents.py
- src/caselawclient/xquery/set_metadata_jurisdiction.xqy
- src/caselawclient/xquery_type_dicts.py
- tests/client/test_get_set_metadata.py
- tests/models/test_documents.py
The General Regulatory Chamber has a number of Jurisdictions (or
'sub-tribunals' as we sometimes call them). These are different to the
separate Lists we see within eg the Chancery Division - Lists are an
administrative distinction, decided on by the court themselves, whereas
Jurisdictions are a statutory one, decided in law. Neither jurisdiction
nor list affects the NCN of the judgment, but they're stored differently
in the XML - Lists are represented in the court code in the uk:court
element, whereas judgments are represented with the uk:jurisdiction
element in addition to the uk:court.
This PR provides accessors for the jurisdiction data, both in isolation,
and combined with the court as a slash-separated string, following the
convention established in the courts metedata in …
> Add methods to set/get jurisdiction of a document, for GRC subdivisions

- .github/pull_request_template.md
- pull_request_template.md
The old PR template wasn't particularly helpful, and was regularly just being wiped.
This replaces it with a new one, which uses the checklist to guide people through necessary considerations so that things aren't missed. It also moves it to the `.github` directory so it's not cluttering the root.
> Make the PR template more useful

- CHANGELOG.md
- pyproject.toml
Minor tweak, but annoyingly technically a breaking change - ensure that document validation works with jurisdictions and that search results return the correct court
> version bump release v22.0.0

- CHANGELOG.md
- script/build_xquery_type_dicts
- smoketest/smoketest.py
- src/caselawclient/Client.py
- src/caselawclient/xquery/get_components_for_document.xqy
- src/caselawclient/xquery_type_dicts.py
- tests/client/test_get_press_summaries_for_document_uri.py
This adds a `get_press_summaries_for_document_uri` which gets press summaries for a document URI. I’ve made the query itself configurable so we can use it for other components too, but for now we’re only using it for press summaries.
As I wasn’t super confident it was going to work, I’ve also added a smoketest, which I think it worth having around.
> Add a helper to get press summaries for a document

- CHANGELOG.md
- smoketest/smoketest.py
- src/caselawclient/Client.py
- src/caselawclient/models/documents.py
- src/caselawclient/xquery/validate_document.xqy
- src/caselawclient/xquery_type_dicts.py
- tests/client/test_validate_document.py
- tests/models/test_documents.py
This adds a `validates_against_schema` property to a document, and adds the logic to `can_enrich` to return true if a document was not recently enriched AND it passes schema validation.
> (1695) Don't enrich when the document does not validate against a schema

- src/caselawclient/models/judgments.py
- src/caselawclient/models/press_summaries.py
- tests/factories.py
- tests/models/test_judgments.py
- tests/models/test_press_summaries.py
This adds the logic to get a linked document to the individual document class. At the moment this is done in the Public UI, which
a) Is hard to mock; and
b) Gives us more to do at the UI end
Keeping the responsibility in the client makes the behaviour more predictable, as well as means we have a “real” document object to get things like the title etc from.
I’ve had to do some jiggery pokery to avoid cyclic imports and return the correct document type, but the tests seem happy
> Get linked document inside Document class

- CHANGELOG.md
- pyproject.toml
- Add an `enriched_recently` property
- Add a `validates_against_schema` property
- Add a `can_enrich` property
- Only enrich if not recently enriched and valid against current schema
- Allow fetching linked docuements for `Judgement`s and `PressSummary`s
> Bump version v22.1.0

- CHANGELOG.md
- src/caselawclient/models/utilities/aws.py
It [was commented](https://my.slack.com/archives/C02TP2L2Z0F/p1711375372312379) that our execution IDs were prefixed with `fcl_ex_id_` -- we can remove that.
> Fix/remove UUID prefix

- src/caselawclient/models/documents.py
- tests/models/test_documents.py
Whilst changing the editor to send at least one document with the crontab, discovered that the process will fail because if a document is rejected (e.g. doesn't have a docx) it never gets the "I tried to send" message.
(We did never send this to the parser, though...)
"We should rename all occurances of last_sent_to_parser" is a fair comment; this would involve changing sql_properties_extract in marklogic and get_pending_parse_for_version.xqy in this repo.
> Always set last sent to parser

- .github/workflows/publish.yml
Having successfully pushed utils up with a password and trusted publisher, I deleted the old API keys as the email told me to. 
> An API token belonging to user dxw was used to upload files to the project ds-caselaw-utils, even though the project has a Trusted Publisher configured. This may have been in error. We recommend removing the API token and only using the Trusted Publisher to publish.
> If you are the owner of this token, you can delete it by going to your API tokens configuration and deleting the token named ds-caselaw-utils.
Now api-client won't upload with a:
```
Uploading distributions to https://upload.pypi.org/legacy/
Uploading ds_caselaw_marklogic_api_client-24.0.1-py3-none-any.whl
WARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR …
```
> Speculative: Remove old auth from PyPI

- .github/workflows/publish.yml
- README.md
Following on from https://github.com/nationalarchives/ds-caselaw-custom-api-client/pull/653 it looks like the bit about id-token: write wasn't added to the code.
> Add write permissions

- .github/workflows/test.yml
Add Python 3.13 to test matrix
This is in readiness for the release of Python 3.13 in a few months, so we get early warning of issues.
> [FCL-270] Add Python 3.13 to test matrix

- .pre-commit-config.yaml
- CHANGELOG.md
- pyproject.toml
- Multiple methods which used to be within `Document` are now in `Document.body`
- **FCL-268**: break functions which rely on the document body into their own subclass
- **FCL-268**: update factory behaviour to match new document body model
- **FCL-268**: use real date when testing if document date should be sent in reparse payload
- **deps**: update dependency boto3 to v1.35.23
- **FCL-268**: move document statuses to their own submodule
- **FCL-268**: move document exceptions into their own submodule
- **FCL-268**: move XML manipulation into its own file
- **FCL-268**: move the documents module in readiness for better code separation
> Release v26.0.0

- pyproject.toml
- src/caselawclient/Client.py
- src/caselawclient/models/documents/__init__.py
- src/caselawclient/models/documents/body.py
- src/caselawclient/models/neutral_citation_mixin.py
- src/caselawclient/models/utilities/dates.py
- tests/client/test_advanced_search.py
- tests/client/test_checkout_checkin_judgment.py
- tests/client/test_eval_xslt.py
- tests/client/test_save_copy_delete_judgment.py
- tests/client/test_verify_show_unpublished.py
- tests/factories.py
- tests/models/documents/test_documents.py
Some upcoming changes to factory methods reveal unnecessary code complexity; to combat this add the `SIM` rules to the ruff configuration and adjust code accordingly.
> [FCL-340] Add code simplification rules to ruff in API Client and make necessary adjustments

- CHANGELOG.md
- src/caselawclient/responses/search_response.py
- tests/responses/test_search_response.py
The total number of results is inherently an integer, and we should treat it as such.
> fix(SearchResponse): total now returns an int, not a str

- CHANGELOG.md
- src/caselawclient/Client.py
- src/caselawclient/models/documents/__init__.py
- src/caselawclient/models/utilities/move.py
- tests/models/utilities/test_utilities.py
Remove `Document.overwrite` and `MarklogicApiClient.overwrite` methods, and associated move utility methods. These are never used downstream, and contained a call to an undefined method which would have raised a runtime error.
BREAKING CHANGE: Remove `Document.overwrite` and `MarkLogicApiClient.overwrite`
> Breaking: Remove unused overwrite methods

- CHANGELOG.md
- pyproject.toml
- Remove `Document.overwrite` and `MarkLogicApiClient.overwrite`
- The `models.documents.body.CourtIdentifierString` type has been replaced with the more specific `courts.CourtCode` type from ds-caselaw-utils.
- **NeutralCitationMixin**: use ABC to flag abstract methods properly
- **deps**: update dependency boto3 to v1.35.33
- **deps**: update dependency mypy-boto3-s3 to v1.35.32
- **deps**: update dependency boto3 to v1.35.30
- **SearchResponse**: total now returns an int, not a str
- **SearchResult**: update behaviour to meet type checking
- **deps**: update dependency ds-caselaw-utils to v1.7.0
- **deps**: update dependency boto3 to v1.35.28
- **deps**: update dependency ds-caselaw-utils to v1.5.7
- **FCL-331**: move api_client, xml and html params to build method signature instead of …
> bump: version 26.0.0 → 27.0.0

- src/caselawclient/factories.py
- tests/test_factories.py
The object created by DocumentFactory.build() could not have `.content_as_html` run on it because the Document class was unpatched before the function was left. (Instead we just slap a static Mock on the individual object)
> fix content_as_html

- .github/workflows/test.yml
Improve our testing strategy by now including Python 3.14 in the test matrix, and also allowing tests on Python 3.13 and 3.14 (which are not yet targeted for support) to fail without cancelling the entire test job.
FCL-394
> [FCL-394] Allow test failures for Python 3.13 and 3.14

- CHANGELOG.md
- src/caselawclient/models/documents/__init__.py
- tests/models/documents/test_documents.py
> Erroneous doc.body attribute calls on body work with a warning

- CHANGELOG.md
- src/caselawclient/Client.py
- tests/client/test_checkout_checkin_judgment.py
In order to support automatic unlocking of enriched judgments before the editors start work in the morning, allow a fixed amount of time before automatically unlocking the judgment.
Once used in the privileged API, this should prevent enrichment leaving editors with locked judgments when enrichment fails.
> Lock judgment with fixed timeout

- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
- src/caselawclient/models/documents/body.py
- src/caselawclient/models/documents/transforms/html.xsl
- tests/models/documents/test_document_body.py
- tests/models/documents/xslt/test_standard_judgment.html
- tests/models/documents/xslt/test_standard_judgment.xml
This will allow us to run XSLT operations in the application itself, rather than handing it off to MarkLogic. This makes the process more easily testable and observable.
FCL-386
> [FCL-386] Add native XSLT transformations to the API

- .github/workflows/docs.yml
We were previously installing absolutely every dependency to build API documentation; now we install the bare minimum of `pdoc` (and its dependencies).
> Only install minimum requirements to build API documentation

- src/caselawclient/Client.py
- src/caselawclient/models/documents/__init__.py
- src/caselawclient/models/documents/transforms/html.xsl
- src/caselawclient/xquery/get_judgment.xqy
- src/caselawclient/xquery_type_dicts.py
- tests/models/documents/test_documents.py
- tests/models/test_judgments.py
- tests/models/test_press_summaries.py
Change the behaviour of search query highlighting so that it happens when the document is retrieved, not when it's transformed into HTML.
FCL-396
> [FCL-396] Change search query highlighting behaviour

- CHANGELOG.md
- pyproject.toml
- **FCL-396**: query highlighting is now done as a function of requesting the Document
- **deps**: update dependency boto3 to v1.35.48
- **deps**: update dependency mypy-boto3-s3 to v1.35.45
- **deps**: update dependency boto3 to v1.35.45
- **FCL-396**: tidy up API implementation for search query highlighting change
> bump: version 27.1.0 → 27.2.0

- CHANGELOG.md
- src/caselawclient/Client.py
- tests/client/test_get_document_by_uri.py
This is necessary to support constructing documents with query highlighting.
> [FCL-386] Search query can now be passed to get_document_by_uri

- CHANGELOG.md
- pyproject.toml
- **FCL-386**: search query can now be passed to get_document_by_uri
> bump: version 27.2.0 → 27.3.0

- src/caselawclient/Client.py
If the `DEBUG` environment variable isn't blank or empty, display the arguments passed to xquery files.
```
service-1  | Sending {"uri": "/failures/BULK-0.xml", "annotation": "Judgment locked for editing by dragon at 2024-11-06T17:08:41.872618+00:00 for 1 seconds", "timeout": 1} to /app/.venv/lib/python3.12/site-packages/caselawclient/xquery/checkout_judgment.xqy
service-1  | Sending {"user": "dragon", "role": "admin"} to /app/.venv/lib/python3.12/site-packages/caselawclient/xquery/user_has_role.xqy
service-1  | Sending {"uri": "/failures/BULK-0.xml", "version_uri": null, "show_unpublished": true, "search_query": null} to /app/.venv/lib/python3.12/site-packages/caselawclient/xquery/get_judgment.xqy
```
> Add DEBUG logging

- .pre-commit-config.yaml
Pre-commit complained:
> [WARNING] hook id `commitizen-branch` uses deprecated stage names (push) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
We run that command.
> Fix precommit warning about push stage

- .pre-commit-config.yaml
- src/caselawclient/models/judgments.py
- src/caselawclient/models/press_summaries.py
- tests/client/test_advanced_search.py
- tests/client/test_checkout_checkin_judgment.py
- tests/client/test_client.py
- tests/client/test_eval_xslt.py
- tests/client/test_get_document_by_uri.py
- tests/client/test_get_judgment_and_versions.py
- tests/client/test_get_press_summaries_for_document_uri.py
- tests/client/test_get_set_metadata.py
- tests/client/test_get_set_properties.py
- tests/client/test_get_version_annotation.py
- tests/client/test_get_version_created_datetime.py
- tests/client/test_save_copy_delete_judgment.py
- tests/client/test_user_privileges.py
- tests/client/test_validate_document.py
- tests/models/documents/test_document_body.py
- tests/models/documents/test_document_validation.py
- tests/models/documents/test_document_verbs.py
- tests/models/documents/test_documents.py
- tests/models/test_judgments.py
- tests/models/test_press_summaries.py
- tests/models/utilities/test_utilities.py
- tests/responses/test_search_result.py
- tests/test_factories.py
Due to a misconfiguration tests weren't being type checked against the actual library code; this is no longer the case, and tests must meet all type constraints.
> Make tests pass mypy type checking

- CHANGELOG.md
- src/caselawclient/Client.py
- src/caselawclient/factories.py
- src/caselawclient/models/documents/__init__.py
- src/caselawclient/models/documents/exceptions.py
- src/caselawclient/models/judgments.py
- src/caselawclient/models/press_summaries.py
- src/caselawclient/models/utilities/__init__.py
- src/caselawclient/xquery/get_components_for_document.xqy
- tests/client/test_checkout_checkin_judgment.py
- tests/client/test_client.py
- tests/client/test_eval_xslt.py
- tests/client/test_get_judgment_and_versions.py
- tests/client/test_get_press_summaries_for_document_uri.py
- tests/client/test_get_set_metadata.py
- tests/client/test_get_set_properties.py
- tests/client/test_get_version_annotation.py
- tests/client/test_get_version_created_datetime.py
- tests/client/test_save_copy_delete_judgment.py
- tests/client/test_validate_document.py
- tests/models/documents/test_document_verbs.py
- tests/models/documents/test_documents.py
- tests/models/test_judgments.py
- tests/models/test_press_summaries.py
- tests/models/utilities/test_utilities.py
This previously accepted a str and would attempt to strip it and remove slashes. It now only accepts a `DocumentURIString` object.
To enforce this, `DocumentURIString` is now a subclass of `str` which will validate incoming strings on creation time and raise an exception if they don't match the expected format.
BREAKING CHANGE: Document can now no longer be initialised with a string as the `uri`, it must be a `DocumentURIString`.
> [FCL-461] Initialising a Document now requires a DocumentURIString, not a str

- CHANGELOG.md
- pyproject.toml
- Code which provided unsanitised URIs when initialising `DocumentURIStrings` will now cause `InvalidDocumentURIException`s to be raised.
- Document can now no longer be initialised with a string as the `uri`, it must be a `DocumentURIString`.
- Validate strings when creating a new DocumentURIString
- **deps**: update dependency boto3 to v1.35.58
- **deps**: update dependency boto3 to v1.35.56
- **Document**: initialising a Document now requires a DocumentURIString, not a str
- **tests**: simpler test changes to pass type checking
> bump: version 27.4.0 → 28.0.0

- .pre-commit-config.yaml
- CHANGELOG.md
- src/caselawclient/models/documents/xml.py
- src/caselawclient/xml_helpers.py
- Add the `types-lxml` library to mypy so that it can perform type checking on interactions with lxml.
> Enforce type-safe behaviour using lxml

- CHANGELOG.md
- src/caselawclient/Client.py
- src/caselawclient/factories.py
- src/caselawclient/models/documents/__init__.py
- src/caselawclient/models/identifiers/__init__.py
- src/caselawclient/models/identifiers/neutral_citation.py
- src/caselawclient/models/identifiers/unpacker.py
- src/caselawclient/xquery/get_property_as_node.xqy
- src/caselawclient/xquery/set_property_as_node.xqy
- src/caselawclient/xquery_type_dicts.py
- tests/conftest.py
- tests/models/documents/test_document_identifiers.py
- tests/models/identifiers/test_identifer_unpacking.py
- tests/models/identifiers/test_identifier_ncns.py
- tests/models/identifiers/test_identifiers.py
> [FCL-309] Add the ability for documents to store abstract identifiers in MarkLogic properties

- CHANGELOG.md
- src/caselawclient/models/documents/__init__.py
- src/caselawclient/models/identifiers/__init__.py
- src/caselawclient/models/identifiers/unpacker.py
- tests/models/documents/test_document_identifiers.py
- tests/models/identifiers/test_identifer_unpacking.py
- tests/models/identifiers/test_identifiers.py
Add basic crud on Document.Identifiers
On top of https://github.com/nationalarchives/ds-caselaw-custom-api-client/pull/778
> Fcl 309 Add CRUD functions to identifiers

- script/build_xquery_type_dicts
- src/caselawclient/Client.py
- src/caselawclient/identifier_resolution.py
- src/caselawclient/xquery/resolve_from_identifier.xqy
- src/caselawclient/xquery_type_dicts.py
- tests/client/test_identifier_resolution.py
Functions to take a PUI url matching an identifier's URI and return the MarkLogic URI.
https://national-archives.atlassian.net/browse/FCL-496
> Resolve identifier URIs to MarkLogic URIs

- src/caselawclient/models/documents/__init__.py
- src/caselawclient/models/identifiers/__init__.py
- tests/models/documents/test_document_verbs.py
Move saving identifiers to the document
> Use save_identifiers on document not identifiers.save()

- CHANGELOG.md
- pyproject.toml
- **FCL-309**: identifier UUIDs are now prefixed with 'id-'
- **FCL-309**: identifiers can compile URL slugs
- **FCL-309**: identifiers can now be saved to and retrieved from MarkLogic
- **FCL-309**: add functionality for packing and unpacking XML representations of identifiers
- **FCL-309**: add stub for defining identifier schemas, and a Neutral Citation schema
- **deps**: update boto packages to v1.35.69
- **deps**: update dependency ds-caselaw-utils to v2.0.1
- **deps**: update dependency mypy-boto3-sns to v1.35.68
- **deps**: update boto packages to v1.35.67
- **deps**: update dependency boto3 to v1.35.64
- **deps**: update boto packages to v1.35.61
- **deps**: update dependency boto3 to v1.35.77
- **deps**: update dependency mypy-boto3-s3 to v1.35.76
- **deps**: update dependency …
> bump: version 28.0.0 → 28.1.0

- poetry.lock
- pyproject.toml
- src/caselawclient/Client.py
- src/caselawclient/models/documents/__init__.py
- src/caselawclient/models/identifiers/__init__.py
- src/caselawclient/models/identifiers/fclid.py
- src/caselawclient/models/identifiers/unpacker.py
- src/caselawclient/xquery/get_next_document_sequence_number.xqy
- tests/conftest.py
- tests/models/documents/test_document_verbs.py
- tests/models/identifiers/test_identifiers.py
- Adds a new FCLID identifier class
- Adds new `Client` method for getting the next sequence number from MarkLogic
- Calling `Document.publish()` will now assign the document a FCLID if one doesn't already exist.
> [FCL-499, FCL-532] Add IdentifierSchema for creating SQID-based Find Case Law Identifiers

- CHANGELOG.md
- pyproject.toml
- **FCL-532**: assign FCLIDs on document publication
- **FCL-532**: add ability to retrieve identifiers by type
- **FCL-499**: add new FCLID identifier class
- **FCL-499**: add method to get next sequence number from MarkLogic
- **deps**: update dependency certifi to >=2024.12.14,<2024.13.0
- **deps**: update dependency boto3 to v1.35.80
> bump: version 28.1.0 → 28.2.0

- CHANGELOG.md
- pyproject.toml
- Methods which were previously guaranteed to return a Neutral Citation may now return `None`.
- **FCL-533**: getting scored or preferred identifiers can now be done by type
- **FCL-533**: modify human identifier to rely on identifiers framework
- **FCL-533**: add scoring to Identifiers
- **IdentifierSchema**: use hasattr instead of getattr with a default when testing required attributes
> bump: version 28.2.0 → 29.0.0

- src/caselawclient/models/identifiers/__init__.py
- src/caselawclient/models/utilities/aws.py
- tests/models/identifiers/test_identifiers.py
Before:
Make str(identifier) be something that's printable in the website, rather than falling back to the repr
> str(identifier) should be just the value

- CHANGELOG.md
- src/caselawclient/models/identifiers/press_summary_ncn.py
- tests/models/identifiers/test_identifier_press_summaries.py
This adds a new identifier schema for relating Press Summaries to judgments.
This isn't a perfect solution - this kind of thing would ideally be handled by proper document relations and resolution code - but it does solve the problem in the short term without us needing to also add a whole new system for handling relations.
> [FCL-568] Add new class for Press Summary identifiers

- CHANGELOG.md
- pyproject.toml
- **FCL-568**: add new class for Press Summary identifiers
- **deps**: update dependency mypy-boto3-s3 to v1.35.92
- **deps**: update dependency boto3 to v1.35.91
- **deps**: update dependency boto3 to v1.35.88
- **deps**: update dependency charset-normalizer to v3.4.1
- **deps**: update dependency boto3 to v1.35.87
- **deps**: update dependency boto3 to v1.35.85
> bump: version 29.0.1 → 29.1.0

- src/caselawclient/xquery/get_judgment.xqy
When a search query occurs for a string that occurs in the upper part of the XML, it would be corrupted, e.g.
`<uk:cite>[2024] <uk:mark id="mark_1">UKSC</uk:mark> 1</uk:cite>`
if the search query included a word from the contained string.
<s>This removes all such tags, leaving a gap if there was a match, so this will break the JS which expects a mark_1 to exist.</s> Fixed.
Pondered whether <ref> tags are affected. They work fine, but we should be wary of how we handle any tag which contains text in the body of the judgment -- e.g. <neutralCitation>, <docketNumber> in a PUI context.
This only affects PUI -- EUI does not use queries. Otherwise we could have got into a horrid situation where the editor saves back a modified XML... *shudder*
> Remove query mark tags from meta section of XML

- poetry.lock
- pyproject.toml
Pinning to ^0.12.0 was preventing a downstream user from upgrading django-environ. Since this client has no particular reason to be pinned to 0.12, we can loosen this restriction to >=0.12.0.
FCL-611
> build(django-environ): loosen django-environ version pinning

- CHANGELOG.md
- src/caselawclient/models/documents/__init__.py
- src/caselawclient/models/utilities/aws.py
- tests/models/utilities/test_utilities.py
https://national-archives.atlassian.net/browse/FCL-617
We noticed that when publishing ewca/civ/2023/1 the editor was causing every document to be copied from the unpublished assets bucket to the published assets bucket that started with this prefix; this includes files such as ewca/civ/2023/1000/image1.jpg
> Ensure publishing documents only looks in s3 'folder'

- CHANGELOG.md
- pyproject.toml
- **NeutralCitationMixin**: NCNs are no longer considered obligatory
- **s3**: When publishing, only copy files in folder, not all folders that share a prefix
- **deps**: update dependency boto3 to v1.36.6
- **deps**: update boto packages to v1.36.3
> bump: version 29.1.1 → 29.2.0

- CHANGELOG.md
- script/build_xquery_type_dicts
- src/caselawclient/Client.py
- src/caselawclient/factories.py
- src/caselawclient/identifier_resolution.py
- src/caselawclient/models/documents/__init__.py
- src/caselawclient/models/documents/exceptions.py
- src/caselawclient/models/judgments.py
- src/caselawclient/models/press_summaries.py
- src/caselawclient/models/utilities/aws.py
- src/caselawclient/models/utilities/move.py
- src/caselawclient/responses/search_result.py
- src/caselawclient/types.py
- src/caselawclient/xquery_type_dicts.py
- tests/models/documents/test_documents.py
To fix a circular import, we move DocumentURIString and associated exceptions into a new types file at the root of the structure. **This is a breaking change.**
> ⚠️ Refactor DocumentURIString to .types

- CHANGELOG.md
- src/caselawclient/models/documents/body.py
- tests/models/documents/test_document_body.py
- tests/models/documents/xslt/test_standard_judgment.html
- tests/models/documents/xslt/test_standard_judgment.xml
If there is no parsed DOCX in the XML (i.e. there is no content in the header or body) `Document.body.content_as_html` now returns `None`.
This will cause typing changes downstream as it's now an `Optional[str]`
You can pre-emptively check with `Document.body.has_actual_content`
https://national-archives.atlassian.net/browse/FCL-640
> ⚠️ document.body.content_as_html can be None

- src/caselawclient/models/documents/body.py
- tests/models/documents/test_document_body.py
There were many errors on PUI caused by the examples having short XML which doesn't have `header` or `judgmentBody` tags. Let's be casual about what we expect to receive.
> Relax has_content to not require valid akomaNtoso

- src/caselawclient/factories.py
- src/caselawclient/models/documents/__init__.py
- tests/models/documents/test_documents.py
- tests/test_factories.py
BREAKING CHANGE: Remove `content_as_html` and `number_of_mentions` methods from `Document`. Use those on `Document.body` instead.
> refactor(Document): remove deprecated content_as_html and number_of_mentions methods

- src/caselawclient/factories.py
This allows the default body of a Document created by DocumentFactory to pass the 'has content' check.
> fix(DocumentFactory): make default body XML representative of a real document

- script/build_xquery_type_dicts
- src/caselawclient/factories.py
- src/caselawclient/identifier_resolution.py
- src/caselawclient/models/documents/__init__.py
- src/caselawclient/models/judgments.py
- src/caselawclient/models/press_summaries.py
- src/caselawclient/types.py
- src/caselawclient/xquery_type_dicts.py
- tests/models/documents/test_documents.py
https://national-archives.atlassian.net/browse/FCL-582
> FCL 582 Get related documents (e.g. Press Summary for Judgment)

- CHANGELOG.md
- src/caselawclient/xquery/xslt_transform.xqy
When searching for a name, e.g. `Huw Evans`, the search highlighting highlights the space, but the transform deletes the whitespace, leaving it with
`<mark id="mark_0">Huw</mark><mark id="mark_1"></mark><mark id="mark_2">Evans</mark>`
This change retains the space
`<mark id="mark_0">Huw</mark><mark id="mark_1"> </mark><mark id="mark_2">Evans</mark>`
I don't understand the difference between `*` and `@*` and `node()`, but this seems to work.
(`@*` is [attributes](https://stackoverflow.com/questions/2942989/what-is-the-at-symbol-used-for-in-xslt)... not sure how that ever worked)
https://stackoverflow.com/questions/2942989/what-is-the-at-symbol-used-for-in-xslt
https://national-archives.atlassian.net/jira/software/projects/FCL/boards/136/backlog?selectedIssue=FCL-628
> Fix missing space when query contains space

- CHANGELOG.md
- script/build_xquery_type_dicts
- src/caselawclient/Client.py
- src/caselawclient/identifier_resolution.py
- src/caselawclient/types.py
- src/caselawclient/xquery/resolve_from_identifier_slug.xqy
- src/caselawclient/xquery_type_dicts.py
We create two new types: `DocumentIdentifierSlug` and `Value`.
> fix(IdentifierResolution): Be explicit about the public URLs being different than the MarkLogic URIs with new types

- src/caselawclient/types.py
- tests/client/test_identifier_resolution.py
- tests/test_types.py
We need to be able to switch both directions between a DocumentURIString (`uksc/2024/1`) and a MarklogicDocumentURIString (`/uksc/2024/1.xml`)
> [FCL-667] Retrieve a DocumentURIString from a MarkLogic one

- CHANGELOG.md
- pyproject.toml
- **types**: MarkLogicDocumentURIString now validates and can be converted back to a DocumentURIString
- **deps**: update boto packages to v1.36.15
- **IdentifierResolution**: fix incorrect types in resolving an identifier
> bump: version 31.0.1 → 31.1.0

- src/caselawclient/models/identifiers/__init__.py
- src/caselawclient/models/identifiers/fclid.py
- src/caselawclient/models/identifiers/neutral_citation.py
- src/caselawclient/models/identifiers/press_summary_ncn.py
- tests/models/identifiers/test_identifiers.py
We now specify stricter types on `Identifier.value` and `IdentifierSchema.slug` so they match up with other functions relying on strict inputs.
> feat(Identifier): update the types of outputs from value and slug

- CHANGELOG.md
- src/caselawclient/models/documents/__init__.py
- tests/models/documents/test_document_verbs.py
- tests/models/documents/test_documents.py
https://national-archives.atlassian.net/browse/FCL-697
- Stop validating xml against schema before triggering enrichment
- Add logging for enrich method for debugging
> Stop validating xml against schema before triggering enrichment

- CHANGELOG.md
- pyproject.toml
- src/caselawclient/xquery/update_locked_judgment.xqy
https://national-archives.atlassian.net/browse/FCL-697
Stop validating xml against schema when attempting to update a locked judgment
> Stop validating xml against schema when attempting to update a locked judgment

- poetry.lock
- pyproject.toml
https://github.com/nationalarchives/ds-caselaw-custom-api-client/security/dependabot/18
Ran poetry upgrade to get lock file up-to-date: also incidently updates utils to 2.3.0
Update poetry versions whilst here:
- Updating rpds-py (0.22.3 -> 0.23.1)
- Updating botocore (1.36.17 -> 1.37.3)
- Updating s3transfer (0.11.2 -> 0.11.3)
- Updating boto3 (1.36.17 -> 1.37.3)
- Updating aws-sam-translator (1.94.0 -> 1.95.0)
- Updating cryptography (43.0.3 -> 44.0.1)
- Updating cfn-lint (1.24.0 -> 1.26.1)
- Updating joserfc (1.0.3 -> 1.0.4)
- Updating setuptools (75.8.0 -> 75.8.2)
- Updating ds-caselaw-utils (2.2.1 -> 2.3.0)
- Updating moto (5.0.28 -> 5.1.0)
- Updating mypy-boto3-s3 (1.36.15 -> 1.37.0)
- Updating mypy-boto3-sns (1.36.3 -> 1.37.0)
> Avoid insecure cryptography package by pinning minimum python to 3.9.2

- src/caselawclient/Client.py
- tests/conftest.py
[Changes to the search](https://github.com/nationalarchives/ds-caselaw-marklogic/pull/158) may mean that search will return XML with an encoding declaration, but the way we absorb that XML in the API client is incorrect -- we get it as a `str` which means that it's already abstract unicode rather than undecoded bytes, and lxml correctly (and annoyingly) tells us it doesn't want to parse abstract unicode as if it's undecoded UTF-8.
The solution is to return bytestrings, which so long as consumers aren't looking too carefully into the types it gets from the API client and just passing them to lxml or similar should be absolutely fine.
This should be safe to run with or without the marklogic changes which depend on them.
This code runs with no errors to demonstrate the problem:
```python …
```
> Provide bytestrings when we're producing search XML.

- CHANGELOG.md
- src/caselawclient/Client.py
- src/caselawclient/client_helpers/__init__.py
- src/caselawclient/models/documents/__init__.py
- src/caselawclient/models/judgments.py
- src/caselawclient/models/press_summaries.py
- src/caselawclient/xquery/insert_document.xqy
- src/caselawclient/xquery_type_dicts.py
- tests/client/test_save_copy_delete_judgment.py
- tests/client_helpers/test_get_document_type_class.py
This removes the reliance on a document's URI to determine its type collection in MarkLogic. This is now derived directly from the XML itself.
BREAKING CHANGE: `insert_document_xml()` now requires a Document type class be provided
> ⚠️ [FCL-735] Inserting a new document requires an explicit document type collection

- CHANGELOG.md
- src/caselawclient/responses/search_result.py
- tests/responses/test_search_result.py
`SearchResults.identifiers` returns a list of identifiers.
Could do with e2e tests at some point in the future once everything leading up to this point is pushed up; confirming all the different components are working together.
Contains a commit from a previous PR because it depends on that work.
> Return identifiers in search results

- CHANGELOG.md
- pyproject.toml
- Python versions below 3.10 are no longer supported.
- `insert_document_xml()` now requires a Document type class be provided
- **FCL-735**: inserting a new document requires an explicit document type collection
- `SearchResults` now includes an `identifiers` property
- **deps**: update dependency boto3 to v1.37.3
> bump: version 33.0.0 → 34.0.0

- src/caselawclient/responses/search_result.py
- tests/responses/test_search_result.py
Currently the code counting the number of nodes to check it's 1 accidently returns True instead, so creates an error message every time.
> fix incorrectly counted `identifiers` node

- src/caselawclient/client_helpers/__init__.py
- src/caselawclient/models/parser_logs.py
- tests/client_helpers/test_get_document_type_class.py
- tests/models/test_parser_logs.py
We get an error that `Document.collection_type_name` doesn't exist. Create a new type to handle the parser logs, so they can have a sensible value.
> Add a ParserLog Document type

- CHANGELOG.md
- src/caselawclient/Client.py
- tests/client/test_get_document_by_uri.py
Documents in the database can have no relevant type (i.e. old parser logs.) We should not block getting the document if that's the case.
> Return Document if an XML document has no relevant collection

- CHANGELOG.md
- src/caselawclient/models/utilities/aws.py
We were getting 
`ClientError An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.` [[rollbar](https://app.rollbar.com/a/dxw/fix/item/tna-caselaw-ingester/136?utm_source=rollbar-notification&utm_medium=slack&utm_campaign=exp_repeat_item_message)]
This is probably caused by trying to pass None as the AccessKey when establishing the api_client. This should be entirely unnecessary.
> None not acceptable Access Key ID -- omit entirely

- src/caselawclient/models/utilities/aws.py
We should be able to configure these in localstack with the correct magic environment variable names
This will break localstack but should not impact any staging/production services.
> Remove env var config for aws

- CHANGELOG.md
- pyproject.toml
- **identifiers**: swap priorities of FCLID and PressSummaryRelatedNCNIdentifier
- **deps**: update dependency boto3 to v1.37.34
- **deps**: update dependency lxml to v5.3.2
- **deps**: update dependency boto3 to v1.37.31
- **deps**: update dependency typing-extensions to v4.13.2
> bump: version 35.0.0 → 35.1.0

- CHANGELOG.md
- pyproject.toml
- src/caselawclient/models/utilities/aws.py
Reinstate environment variable so AWS knows what region it's in
Also bumps version
https://national-archives.atlassian.net/browse/FCL-799
> [FCL-799] Reinstate PRIVATE_ASSET_BUCKET_REGION

- CHANGELOG.md
- src/caselawclient/factories.py
- src/caselawclient/models/identifiers/__init__.py
- src/caselawclient/models/identifiers/exceptions.py
- src/caselawclient/models/identifiers/unpacker.py
- tests/models/documents/test_document_verbs.py
- tests/models/documents/test_documents.py
- tests/models/identifiers/test_identifiers.py
- tests/models/test_judgments.py
- tests/models/test_press_summaries.py
We aren't currently checking that identifier values are valid when we try to initialise the object. We should do so, so that we can't then save invalid identifier values to the database.
This PR adds running the `schema.validate_identifier()` method to the `__init__` method for `Identifier`s (with attendant test changes, now that test identifiers must also be valid).
FCL-818
> [FCL-818] Make sure values are validated when Identifier objects are created

- CHANGELOG.md
- src/caselawclient/factories.py
- src/caselawclient/identifier_resolution.py
- tests/client/test_identifier_resolution.py
- tests/models/documents/test_documents.py
The related documents panel on PUI was not showing up because document_published was always false, because MarkLogic emits a JSON `True` not string `"True"`
> Identifier's document_published is a boolean out of MarkLogic

- CHANGELOG.md
- pyproject.toml
- An identifier's document_published is natively boolean from MarkLogic, treat it as such
- `NeutralCitationNumber`s must now be valid in all conditions, including under test.
- **NeutralCitationNumber**: validating an NCN now checks it can be converted to a URL
- **Identifiers**: run identifier validation methods on init
> bump: version 35.1.1 → 36.0.0

- src/caselawclient/factories.py
Make the `SearchResultFactory` defaults more closely match the output of a real search, so we can use them downstream in other services as a reliable stand-in.
FCL-833
> [FCL-833] Improve Search factory output

- CHANGELOG.md
- pyproject.toml
- **SearchResultFactory**: now closer matches a real `SearchResult` so it's more useful downstream
> bump: version 36.0.0 → 36.0.1

- CHANGELOG.md
- src/caselawclient/models/documents/__init__.py
- src/caselawclient/models/documents/body.py
- src/caselawclient/models/documents/transforms/html.xsl
- tests/models/documents/test_document_body.py
- tests/models/documents/test_documents.py
- tests/models/documents/xslt/test_standard_judgment.html
https://national-archives.atlassian.net/browse/FCL-822
Breaking change -- we change the signature of content_as_html to take uri paths, not asset domains and make the prefix mandatory, and rename it to content_html to avoid broken functionality by causing more major errors where it hasn't been updated.
> ⚠️ Fix asset location

- CHANGELOG.md
- pyproject.toml
- src/caselawclient/factories.py
We were returning a `str` when we should have been returning a `datetime`.
> Fix incorrect return type in SearchResultFactory

- CHANGELOG.md
- src/caselawclient/Client.py
- src/caselawclient/models/documents/__init__.py
- src/caselawclient/xquery/get_missing_fclid.xqy
- src/caselawclient/xquery_type_dicts.py
To support being able to issue FCLIDs to all documents without them:
- Make safe FCLID minting its own function
- Add query to retrieve documents without an FCLID
> [FCL-49] Add supporting functions for issuing FCLIDs to all documents

- CHANGELOG.md
- pyproject.toml
- **MarklogicApiClient**: add new method for getting list of documents missing a FCLID
- **deps**: update dependency ds-caselaw-utils to v2.4.5
- **deps**: update dependency boto3 to v1.38.14
- **deps**: update dependency ds-caselaw-utils to v2.4.4
- break FCLID minting into its own function at document level
> bump: version 37.0.2 → 37.1.0

- CHANGELOG.md
- pyproject.toml
- **SearchResultFactory**: search result factory now includes identifier map
- **deps**: update dependency boto3 to v1.38.17
- **deps**: update dependency sqids to v0.5.2
- **deps**: update dependency ds-caselaw-utils to v2.4.6
> bump: version 37.1.0 → 37.2.0

- CHANGELOG.md
- src/caselawclient/search_parameters.py
- tests/client/test_advanced_search.py
- tests/client/test_search_parameters.py
https://national-archives.atlassian.net/browse/FCL-558
- Add only_with_html_representation field to SearchParameters dataclass so we can pass this argument when making searches from the PUI (specifically for filtering those without html reps from atom feed)
> Add only_with_html_representation field to SearchParameters dataclass

- CHANGELOG.md
- pyproject.toml
- **extract_version**: update version decoding regex so it accepts new-style URIs
- **deps**: update dependency boto3 to v1.38.22
- remove unused namespace declarations from codebase
- **Document**: improve type hints for versions_as_documents
> bump: version 37.3.0 → 37.3.1

- CHANGELOG.md
- src/caselawclient/models/identifiers/__init__.py
- src/caselawclient/models/identifiers/unpacker.py
- tests/models/documents/test_document_identifiers.py
- tests/models/identifiers/test_identifer_unpacking.py
- tests/models/identifiers/test_identifiers.py
This allows us to record the fact that an identifier - although previously used to refer to a document - should no longer be promoted.
> [FCL-886] Add the ability to store and retrieve if an identifier is deprecated

- .github/workflows/docs.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
- CHANGELOG.md
Bump our version of Poetry used from 1.4.2 to 2.1.1.
> Update version of Poetry used in CI

- CHANGELOG.md
- src/caselawclient/models/documents/body.py
- tests/models/documents/test_document_body.py
Adds the case number and category to the document body from the xml if available.
> FCL-890 | add case number and category from xml to document body

- src/caselawclient/factories.py
We can't call `.of_type` on a dict (which I'm planning to do in the PUI), so the factory needs the right types.
Also add an FCL id to the factory.
These are in support of https://github.com/nationalarchives/ds-caselaw-public-ui/pull/2163
> Ensure SearchResultFactory's identifiers are Identifers

- src/caselawclient/models/documents/__init__.py
- src/caselawclient/models/documents/exceptions.py
- tests/models/documents/test_document_verbs.py
If a document doesn't have a docx, it should not be enriched; when enrichment is attempted, fail gracefully but record that an attempt was made to ensure it doesn't block other enrichment.
Difficult to manually test locally -- worth additional scrutiny in staging?
https://national-archives.atlassian.net/jira/software/projects/FCL/boards/136?selectedIssue=FCL-889
> [FCL-889] Don't enrich if no content

- CHANGELOG.md
- src/caselawclient/factories.py
- src/caselawclient/models/identifiers/__init__.py
- src/caselawclient/models/identifiers/collection.py
- src/caselawclient/models/identifiers/unpacker.py
- src/caselawclient/responses/search_result.py
- tests/models/documents/test_document_verbs.py
- tests/models/identifiers/test_identifer_unpacking.py
- tests/models/identifiers/test_identifiers.py
- tests/responses/test_search_result.py
Move where we define the concept of a collection of identifiers around, so we can avoid circular import problems in future.
> [FCL-1007] Refactor identifier collections

- src/caselawclient/models/documents/xml.py
- tests/models/documents/test_document_xml.py
Whilst the XML was correctly namespaced, the apply_xlst function was namespacing far too much in the output bytes (`<akn:FRBRthis xmlns:akn="...">`)
Fix this by canonicalising.
One side effect of canonicalising the XML is that all tags are `<a></a>` rather than `<a/>`
> Canonicalise XML output of apply_xslt to avoid weird namespacing artifacts

- src/caselawclient/models/documents/__init__.py
- tests/models/documents/test_documents.py
We agreed now is a good time to migrate to `/id/doc/tn4t35ts` as a URI.
https://dxw.slack.com/archives/C04FQ3GFGUQ/p1751972123605659
> Use `/id/doc` namespace for work with no `tna.` prefix

- src/caselawclient/models/documents/xml.py
- tests/models/documents/test_document_xml.py
v1 canonicalisation leaves namespaces everywhere -- e.g. <akn:FRBRuri> tags rather than just <FRBRuri> tags so we should use v2, now we've established that the reason for not using v2 was probably incorrect -- the issues were probably caused by not following the schema
Abbrieviated output of canonicalisation methods:
```
etree.tostring(root, method = "c14n")
<akn:FRBRuri xmlns:akn="http://docs.oasis-open.org/legaldocml/ns/akn/3.0" value="https://caselaw.nationalarchives.gov.uk/id/doc/tn4t35ts"></akn:FRBRuri>
etree.tostring(root, method = "c14n2")
<FRBRuri value="https://caselaw.nationalarchives.gov.uk/id/doc/tn4t35ts"></FRBRuri>
etree.canonicalize(root)
<FRBRuri value="https://caselaw.nationalarchives.gov.uk/id/doc/tn4t35ts"></FRBRuri>
```
> Canonicalise with v2

- CHANGELOG.md
- src/caselawclient/models/documents/__init__.py
- src/caselawclient/models/identifiers/__init__.py
- src/caselawclient/models/identifiers/collection.py
- src/caselawclient/models/identifiers/exceptions.py
- tests/models/identifiers/test_identifiers.py
Changes to the API client to support the EUI being able to directly manipulate the list of identifiers.
- FCL-880
- FCL-994
> [FCL-880] Support direct manipulation of identifiers list

- src/caselawclient/xslt/modify_xml_live.xsl
- tests/models/documents/test_documents.py
In order to use v1 canonicalisation to support non-messy ref tags, ensure that we don't insert spurious akn namespaces into the middle of the document.
> Don't insert akn namespaces unnecessarily

- .github/workflows/test.yml
We are moving to CodeCov, but are temporarily removing CodeClimate to unblock CI.
> ci: temporarily remove CodeClimate reporting

- .github/workflows/docs.yml
- src/caselawclient/__init__.py
Previously, the generated documentation was using a static version number for the library (v12). Make it dynamic, so people blindly copying and pasting will always get the latest version.
> Make the package version number in the docs dynamic

- CHANGELOG.md
- src/caselawclient/Client.py
- tests/client/test_advanced_search.py
- tests/client/test_eval_xslt.py
- tests/client/test_verify_show_unpublished.py
`verify_show_unpublished` is typically being called to return a boolean which determines if unpublished documents should be shown: calls to it that fail do not imply a security issue, and this message is spammy and unhelpful.
> May 27 12:32:20 PM [35.176.221.42](https://my.na-01.cloud.solarwinds.com/226497157428851712/logs?q=host%3A%2235.176.221.42%22&focus=1863983586311602192&selected=1863983586311602192) [dxw-dalmatian-caselaw-prod-public-48b33d0444c4](https://my.na-01.cloud.solarwinds.com/226497157428851712/logs?q=program%3A%22dxw-dalmatian-caselaw-prod-public-48b33d0444c4%22&focus=1863983586311602192&selected=1863983586311602192) WARNING 2025-05-27 11:32:20,578 Client 1837 139660198599552 User caselaw-public-ui is attempting to view unpublished judgments but does not have that …
> Remove warning about viewing unpublished judgments

- src/caselawclient/models/utilities/aws.py
Reparsing is hitting issues where documents are 403ing. Further information would be useful.
(This might not be neccessary -- what it should actually do is print the filenames every time, even not on error)
> Add logging for 403 on attempted docx read

- src/caselawclient/Client.py
The reparse process is stopping because an unanticipated XDMP-LOCKED error is being treated as a fatal error.
> Add XDMP-LOCKED as MarklogicResourceLockedError

- src/caselawclient/models/identifiers/__init__.py
- tests/models/identifiers/test_identifier_constraints.py
Duplicate identifier detection wasn't correctly ignoring where the current identifier had been saved to the database. However, this was being masked by also not correctly checking identifiers of unpublished documents.
This PR fixes both.
FCL-1137
> [FCL-1137] Fix adding new identifiers whilst a document is published

- CHANGELOG.md
- src/caselawclient/Client.py
- tests/client/test_checkout_checkin_judgment.py
- tests/client/test_client.py
- tests/client/test_get_set_metadata.py
- tests/client/test_get_set_properties.py
https://national-archives.atlassian.net/jira/software/projects/FCL/boards/136?selectedIssue=FCL-1056
Adds optional environment variables `CONNECT_TIMEOUT` and `READ_TIMEOUT` with default values borrowed from https://requests.readthedocs.io/en/latest/user/advanced/#timeouts (slightly more than a TCP retry window and slightly less than a default gunicorn timeout, respectively)
> Add timeout for marklogic eval

- CHANGELOG.md
- src/caselawclient/responses/search_result.py
- tests/conftest.py
- tests/responses/test_search_result.py
This was previously always returning a `str`, even if that string was `""`. In those cases the API client will now correctly return a `None`.
> [FCL-1178] neutral_citation of a SearchResult will now correctly be None if not present

- src/caselawclient/models/utilities/aws.py
- tests/models/utilities/test_utilities.py
part of https://national-archives.atlassian.net/browse/FCL-1062
`aws.delete_from_bucket` does not seem to have been used or tested; we want to be able to delete items from the bucket that aren't tar.gz files to erase it back to a sensible state. We also rewrite delete from bucket in terms of a function that filters the objects in an S3 prefix.
Non-tar-gz-delete might want to be private bucket only
> Delete only non-tar.gz files from bucket

- CHANGELOG.md
- src/caselawclient/models/documents/__init__.py
- src/caselawclient/models/documents/body.py
- tests/models/documents/test_document_body.py
https://national-archives.atlassian.net/browse/FCL-1132
Using the presence of `uk:party` as a temporary measure before building a proper way of dealing with the additional data, block enrichment and reparsing of documents from the tribunal backlog.
Reparsing is definately needed, enrichment might be safe (but pointless)
> FCL 1132: Block enrichment and reparsing if tribunal backlog

- src/caselawclient/models/identifiers/__init__.py
- src/caselawclient/models/identifiers/collection.py
- tests/models/identifiers/test_identifiers.py
Part of https://national-archives.atlassian.net/browse/FCL-1062
Flesh out the support for future identifier schemas to allow multiple identifiers of a type by adding a property to the schema and updating the "this is allowed" logic
> Multiple identifiers of the same type allowed for future identifier schemas

- CHANGELOG.md
- src/caselawclient/models/documents/__init__.py
- tests/models/documents/test_documents.py
A sentinel value of `1970-01-01 00:00`` indicates that we know a document has previously been published, but not exactly when. `has_ever_been_published` already interprets this correctly, but we add a new test for this.
We also add `first_published_datetime_display` which will return a `None` where the value matches this sentinel, and this can be used in combination with `has_ever_been_published` to indicate an "unknown" state.
> [FCL-1272] first_published_datetime now interprets sentinel values

- CHANGELOG.md
- pyproject.toml
- **Document**: first_published_datetime now interprets sentinel values
- **DocumentFactory**: document factories now correctly set a default first published datetime
- **deps**: update dependency boto3 to v1.40.25
- **deps**: update dependency boto3 to v1.40.22
- **deps**: update dependency ds-caselaw-utils to v2.7.1
- **deps**: update dependency ds-caselaw-utils to v2.7.0
- **deps**: update dependency boto3 to v1.40.20
- **deps**: update dependency boto3 to v1.40.17
- **deps**: update dependency typing-extensions to v4.15.0
- **deps**: update dependency boto3 to v1.40.16
- **deps**: update dependency lxml to v6.0.1
- **deps**: update dependency boto3 to v1.40.13
> bump: version 41.0.0 → 41.1.0
